[#shemini]
=== Shemini

. “And it was on the *eighth day*,” etc. Which day of the month was it?

. What was happening during the seven previous days?

. “That day took ten crowns,” etc. What kind of crowns?

. Moshe called the elders of Israel. What for?

. Why did Aharon have to offer a calf for a Korban?

. Why did Moshe have to urge Aharon, “Come to the mizbeyach!”?

. After the korbanos were offered, what kind of blessing did Aharon give?

. After that blessing Moshe and Aharon went into the ‘holy tent’ again. What for? (Two reasons.)

. How did the people react after they saw the Heavenly fire come down?

. What was the blessing that Moshe and Aharon gave to the people?

. Why did the people feel *embarrassed* as long as the <<Shechina>> (Divine Presence) didn’t come?

. How is the ‘wrong service’ of Nadav and Avihu described in the posuk?

. What are the opinions of Rabbi Eliezer and Rabbi Yishmael about the wrongdoing?

. Hashem’s name was going to be sanctified in public on this great day. What did Moshe expect?

. What did Moshe find out about his greatness (and Aharon’s) after the tragedy?

. How did Aharon react to his sons’ death? How was he rewarded?

. How does Hashem’s name become sanctified through the punishment of tzadikim?

. Who were these people: Mishael, Eltzafan, Uziel? What were the first two asked to do?

. The usual observances of mourners were prohibited to the survivors. What are they? Are these observances kept today?

. Prove that the suffering of a Torah scholar must be shared by all.

. Prove that when a Kohein drinks wine, his avodah becomes posul.

. Who else was prohibited from drinking wine? What if he did? Proof?

. How do we know that Aharon’s other two sons might have died too? What saved them?

. Which korban was burnt? Why was Moshe upset about it?

. What were the reasons for burning this korban? What reason did Moshe suggest?

. To whom was Moshe complaining about the burning? Who answered him? Why him?

. Moshe liked the answer he was given. What was that answer? What were Moshe’s comments?

. How were Aharon’s sons Elazar and Issamar rewarded for accepting the tragedy properly?

. Why did Hashem put restrictions on the Jewish nation but not on other nations?

. How did Moshe explain to the people about the kosher and non kosher animals? Proof?

. What are the two traits that identify the kosher animals?

. How is a kal v’chomer used to determine the status of certain animals?

. How does the Torah teach us about the obligation of cleansing ourselves before Yom Tov?

. What are the signs of kosher fish? Kosher birds?

. Are people allowed to feed non kosher meat to small children? Proof?

. Carrying a sheretz (rodent) is worse than just touching it. How? (Difference between <<tumas magah>> and <<tumas masah>>.)

. A person who has a sheretz for a pet, is he <<tomei>> (impure)? Proof?

. A wooden dish that became tomei, how is it purified? And earthen vessels?

. Prove following:
[upperalpha]
.. Food (grain, etc.) cannot become tomei unless it first becomes wet.
.. In addition to water, food can be made tomei by wine, oil, etc.
.. A <<vlad hatumah>> (second level tumah) cannot bring tumah to keilim, only to food.
.. Water causes food to absorb tumah only if it got wet after it was detached from the ground.

. Why does it mention *here* that Hashem took us out from Mitzrayim?

. What special parsha is read this Shabbos? Why at this time?
