[#tazria]
=== Tazria

. Why are the laws affecting humans written after the laws of animals?

. How long is a woman tomei after the birth of a son? A daughter?

. Why is her impure period stated as ‘in *clear* blood’?

. What kind of korbanos does a woman have to bring when she is cleansed?

. Which one of her korbanos actually causes her to become <<tahor>> (pure)?

. Can any rabbi decide whether <<negayim>> are tomei or tahor? Proof?

. How many hairs have to change to white in order to make the person tomei?

. On which statement does Rashi comment, “I don’t know its meaning”? Why?

. In which case is the person declared tomei immediately? When is he locked up?

. When is a person locked up for a *second time*? For how long?

. Sometimes the person is declared tahor yet must wash (<<towel>>) himself and his clothes. Why?

. After being locked up what has to happen to his <<negah>> to make him tomei? Tahor?

. What is the general difference between these: <<s’ais>>, <<sapachas>>, <<baheres>>?

. May a Kohein decide on a person with a negah by *getting information* about its condition? Proof?

. Is it possible that a person could become tahor even while he has a regular <<tzoraas>>? Explain.

. There are certain days and certain people that a Kohein should refuse to check. Which?

. What are the signs of tumah for a negah on the skin? On the head?

. If a Kohein mistakenly declares a person ‘tahor’ who is really tomei, is it OK?

. Explain these: <<nesek>>, <<bohak>>, <<tzareves>>, <<keireiach>>, <<giveiach>>.

. What is a metzorah supposed to do to his clothes? To his hair? What does he announce?

. What kind of clothes (materials) can develop negayim? What colors are they?

. What is done with a garment that became tomei?

. When is the negah supposed to be washed? If the negah’s coloring remains the same what is done to it? And if the negah darkened somewhat?

. If after washing it, it reappears again what is done to the <<beged>> (garment)?

. If the negah was removed after washing it, what is done to the beged?

. Are there negayim today? Why? How is this connected to the <<Golus>> (Exile)?
