[#tzav]
=== Tzav

. According to Rabbi Shimon, why does it say here ‘<<tzav>>’ (command) instead of ‘daber’ (speak)?

. What does posuk 2 tell us about the fats and limbs?

. If something became posul, does it still burn on the mizbeyach?

. What was the avodah of <<terumas hadeshen>>? When did the Kohein change garments?

. Where was the fire for the menorah lighting taken from? Proof?

. There were two general kinds of Korban Minchah that the Israelites brought. Which?

. If the <<kometz>> from the above Menachos was taken without <<kavana>> (intention), is it OK?

. Can blemished Kohanim eat from the Menachos? Proof?

. There was a certain korban that regular Kohanim brought during their dedication and the Kohein Gadol brought every day. Which was it?

. Who ate the Korban Minchah that Kohanim brought? Proof?

. What can we learn about koshering earthenware and metal dishes from that which is written regarding the Korban Chatos?

. Which of these are <<kedoshim kalim>> and which are <<kodshai kedoshim>>: Chatos, Olah, Asham, Shlomim, Minchah?

. How long is the ‘eating time’ for a Korban Shlomim?

. When is eating a Korban punishable by <<koreis>>?

. What is the punishment for eating <<cheilev>> (forbidden fats)? Blood?

. Which parts of a Korban Shlomim are given to the Kohanim?

. On which commandments does Rashi comment: “There is not (necessarily) a chronological order in the Torah”? Why here?

. “Take Aharon,” etc. How is Moshe supposed to take him?

. “And gather the community at the door of the <<Ohel Moed>>.” What for?

. What special miracle occurred at this gathering?

. Why does Moshe repeat here: “This is the thing that I was commanded to do”?

. On which activity does Rashi remark, “I don’t know where he was commanded on it.”

. The mizbeyach was *cleansed* and *sanctified*. Why both things?

. Besides the shemen hamishcho, what else was put on Aharon and his sons?

. One part of a korban was burned on the mizbeyach *only during the <<miluim>>*. Which?

. Where is there a hint here about the separation of the Kohein Gadol before Yom Kippur?

. “And Aharon and his sons did all the things,” etc. What is the special compliment here?

. What is the special name given to this Shabbos? Why? Special customs?

