title: "Chumash Questions"
description: "Rabbi Wichnin’s Chumash Questions book"
url: "http://www.chumashquestions.org"
author: "Leonid Dubinsky"
email: dub@chumashquestions.org
timezone: "America/New_York"
