title: "Chumash Questions"
description: "Rabbi Wichnin’s Chumash Questions book"
url: "http://www.chumashquestions.org"
author: "Leonid Dubinsky"
email: dub@chumashquestions.org
timezone: "America/New_York"
favicon: favicon-author.png
license: CC by-nc-nd
license-link: http://creativecommons.org/licenses/by-nc-nd/4.0/
home: /book/book/index.html

