[#re-eh]
== Re’eh

. “*Look*, I give before you,” etc. Is this written in the plural or in the singular?

. Can you find a connection (according to the first <<posuk>>) between this parsha and. the month of Elul?

. How are the two mountains, Grizim and Evol, connected with the first <<posuk>>?

. Where is the description of the activities at these mountains? (Try Ki Savo.)

. From the conditions upon which the blessing and the curse depend, could it be proven that Hashem rewards even the good *thoughts* and *decisions*?

. Prove that one who worships idols, it’s as if he abandoned the Torah entirely.

. At Mount Grizim and Evol, what was said first, the curses or the blessings? Proof?

. In what connection is a current city in Eretz Yisroel (besides Jerusalem) mentioned here? (by a different name)?

. When the people crossed the <<Yarden>>, what gave them the security for conquest?

. What is (are) the first big action(s) the Jews must do after conquering the Land?

. When a person uproots idols, how is he supposed to do it? Proof?

. Not just the idols must be destroyed, but also the *<<mizbeyach>>*, *<<matzeivo>>*, the *<<ashairo>>*, and even the *names* of the idols. Explain.

. “Don’t do such (things) to Hashem.” What is being prohibited here?

. What question did Rabbi Yishmael ask here? His answer?

. When were they permitted to bring sacrifices on private altars (<<bamah>>)? What kind of <<korbanos>> did they bring at the bamah?

. What kind of places were Shiloh, Nov, Givon?

. Eliyahu <<Hanavi>> brought a <<korban>> at Mount Karmel. Was it allowed?

. The area where the <<beis-hamikdash>> was built belonged to *one* tribe *and* to *all*. How?

. What kind of cattle could be used for private consumption, but could not be used for milking or wool shearing?

. Which (healthy) animals are kosher to eat but cannot be brought as a <<korban>>?

. “But the blood do not eat,” etc. Why does it have to be mentioned here?

. “Spill it on the ground like water,” Which laws about blood are stated here?

. In Yehoshua’s time, the Jews weren’t able to conquer Jerusalem (fully). Why?

. What are the three possible ways to benefit a Levi?

. Is there an obligation for special treatment for a Levi outside of Eretz Yisroel? Proof? Can you think of a reason for this?

. Prove that the Torah is opposed to straining one’s budget in order to eat meat.

. Prove that during the time of Moshe Rabeinu, the laws of kosher slaughtering were already known. How do we know these laws today?

. Rabbi Yehuda and Rabbi Shimon differ about the urgent prohibition against eating blood. How?

. How do we learn about the reward for keeping difficult prohibitions (and easy ones)?

. “*Guard* and listen,” etc. What is there to guard before listening?

. What strange sight of idol worshipping did Rabbi Akiva see?

. Give three examples for the prohibition against adding to mitzvos?

. Compare the prohibition here (13:1) to one in parshas Vo’eschanan (4:2). (See Rashi’s comments and look out for differences.)

. How can we explain the fact that a false prophet could perform miracles?

. What does this prophet want people to do? What is done to him?

. If it already mentioned the keeping of mitzvos, what is added by “*listening* to His voice?” What is meant by “and to *cleave* to Him”?

. Why is it especially embarrassing for a Jew to abandon tradition?

. “From the idols of the nations, which are *close* to you or *far* from you,” etc. Why mention both?

. What are the six specific prohibitions against favorable treatment of a missionary?

. How does a city turn into an <<ir-hanidachas>> (a deviant city)?

. How is that kind of city punished? And its wealth?

. Which city can never become an <<ir-hanidachas>>? Proof?

. Why does it preface “You are children to Hashem” to the prohibition against making skin cuts and tearing out hair to mourn the dead?

. We are said here to have two kinds of <<kedusha>> (sanctity). What are they?

. What does the general caution of “Don’t eat anything abominable” include (14:3)?

. Which are more numerous, the clean or the unclean animals? Proof?

. What are the two general signs of kosher animals (for large animals)?

. Which cattle product does not require kosher slaughtering in order to be eaten?

. In parshas Shemini, the kosher and non-kosher animals are enumerated. Why are they repeated here?

. “And don’t touch their carcasses.” Prove that this applies during Yom Tov only.

. Which bird has three names? Why are all of the names listed? Which name has a reason to it?

. Which are more numerous, kosher or non-kosher birds? Proof?

. Are there any signs to recognize kosher birds? Kosher fish?

. “Give it to the convert in your city,” etc. May a convert eat non-kosher?

. When you are amongst people who restrict themselves from something permissible, how are you to act in their midst? Proof?

. The prohibition against mixing meat and milk is mentioned three times. Why? (Compare Rashi’s comments here to his comments in Shemos 34:26.)

. Why is the prohibition against cooking the goat in its mother’s milk mentioned near the mitzvoh of <<maaser>>?

. What is the rule about eating <<maaser-sheini>> (where, how, etc)?

. Explain: <<leket>>, <<shikcha>>, <<pe-ah>>, <<hefker>>.

. Why are all the above *exempt* from the obligation of <<maaser>>?

. At the end of each three years, a person must clean out his <<maaser>>. How?

. On the seventh year (Shmittah) *some* loans are cancelled. Which?

. There are two opposing <<pesukim>> concerning the existence of poverty in the future. Explain the contradiction and the answer to it.

. There are two prohibitions here concerning charity. What are they?

. If we are not required to give charity to make the poor person rich, why is it that sometimes we must provide him with horses and servants? How about a <<shidduch>>?

. Is there a mitzvoh to complain to Hashem against someone who refuses to be kind to you? Does the complaining make a difference?

. How many times must you give charity to the same person (if asked again)?

. What is the order of preference given here for giving out <<tzedakah>>?

. If you know that someone really needs help but refuses charity, what should you do?

. What item *cannot* be given as a farewell gift (<<ha-anakah>>) to a freed servant? Proof?

. What reason is given to us for the above mitzvoh?

. What uses are prohibited for a firstborn (<<bechor>>) kosher animal?

. If the <<bechor>> develops a blemish, what can be done with him?

. How do we make sure that <<Pesach>> falls in the spring, not the winter?

. Did the Jews leave <<Mitzrayim>> by night or by day? Explain.

. Which <<korban>> is added to the <<korban-pesach>>? For what purpose?

. Why is <<matzo>> called <<lechem-oni>> (bread of poverty)?

. There are three time-periods in connection with <<korban-pesach>>. What are they?

. When is this part of the parsha read besides this <<Shabbos>>?

. There are two contradictory <<pesukim>> about eating matzoh. How is it resolved?

. Why is the seventh day of <<Pesach>> called <<atzeres>>? (Two reasons.)

. On Yom Tov, Hashem tells us to take care of ‘His four’ and He will take care of ‘our four.’ How?

. What do we derive from here concerning the <<s-chach>> covering for the Sukkah?

. How many times a year do we have to come to the <<beis-hamikdash>>. When?

[discrete]
==== Special
[start=85]
. Why is the month of Elul considered special?

. Why do we blow the shofar during this month?

. What do we add in the davening during Elul?

. What items should be checked in this month?

. What is the proper wish to be expressed in this month?

. Which day is a holiday in this month?

