[#vo-eschanan]
== Vo’eschanan

. <<tzadikim>> could make a request in two ways. Which is the right one?

. “At that time,” etc. What was that appropriate time?

. This is one of *three* places where Moshe *insisted*. On what? Another place?

. “You started showing your servant,” etc. What did He show? When? (Two answers.)

. “And Your strong Hand,” etc. Which Hand? What strength is meant here?

. Besides seeing that ‘good land,’ in general, which specific things did he crave to see?

. Why was Moshe told ‘enough for you.’ in response to his request?

. Was any part of Moshe’s request fulfilled? Which? How?

. “And *command* Yehoshua, and *strengthen* him,” etc. Command to do what? And why did he need special strengthening? How was Moshe to strengthen him?

. How was the problem in the battle of Ei a result of Yehoshua’s failure?

. “And we sat in the valley across from Beis Peor,” “And how Israel observe the laws,” etc. What is the connection?

. Give examples for the prohibition, “Don’t add nor subtract from the mitzvos.”

. When the nations of the world will hear about our laws, what will they say about us?

. “Watch yourself, lest you forget” etc. What may happen as a result?

. What are the warnings about images? About the sun and the moon?

. We were exiled two years prior to a certain time. Which time? Was it a favor?

. How are the events of Tisha B’Av predicted here?

. What is considered ‘like worshiping idols’ even though it isn’t? Why?

. “Ask, please, about the early days,” etc. (4:32) What should we learn from history?

. How tall was Adam? “Was there ever such a *great thing*”? Which thing?

. What are the examples given for these deeds: [.verse]#masos#{ltr}, [.verse]#osos#{ltr}, [.verse]#mofsim#{ltr},
[.verse]#milchamah#{ltr}? (See <<posuk>> 4:34.)

. “You have been *shown to* know that there is nothing besides G-d.” How was it shown?

. In whose merit did we receive so many great favors? (Exodus from Egypt, Torah, Eretz Yisroel)?

. “Then Moshe separated three cities” When did these cities separate?

. Why did Moshe want to separate them now? What is the lesson here?

. “Do not have other gods *before me*.” When? Where?

. Try to notice and mark down the differences between the first and second giving of the Ten Commandments. Example: the reasons for keeping <<Shabbos>>.

. Which one of Rashi’s comments on the Ten Commandments has been incorporated into the davening of <<Shabbos>>?

. Which mitzvos were given to them before <<matan-torah>>? Give two examples.

. In <<posuk>> 5:19 it says “[.verse]#velo-yosof#{ltr}.” What are the two meanings here?

. After the Jews heard the divine voice from <<har-sinai>>, they got fearful. Why? What did they request from Moshe? What did Hashem say about it?

. What ‘wish’ did Hashem express in connection with this request?

. Was Moshe happy about the request? Why? The proof?

. How does Rashi explain the great statement of “<<shma-yisroel>>” (in <<posuk>> 1)?

. “And you shall love Hashem,” etc. Why is it preferable to serve out of love rather than fear?

. “With all your heart,” etc. What is this referring to? (Two meanings.)

. What is meant by “all your soul”? “All your might”? (Two meanings.)

. How does a person get to love Hashem (according to the context here)?

. Why is the word [.verse]#veshinantam#{ltr} used here for the study and teaching of Torah?

. How is the relationship between a <<rebbi>> (teacher) and <<talmid>> (student) described here?

. “And you shall speak (in) them,” etc. What does this add after saying it in the earlier <<posuk>>?

. “When you go to sleep and when you wake up.” What mitzvoh is meant here?

. How does the word <<totafos>> mean tefillin?

. Prove that we aren’t obligated to put mezuzos on *both* doorposts.

. What kinds of gates require mezuzos? Proof?

. What should the Jews expect to find when entering the Holy Land?

. Why is there an immediate *warning* following the above *goodies*?

. Was this kind of warning mentioned elsewhere in this parsha?

. When may a man swear in Hashem’s name? Why only then?

. “And you shall do the righteous and the good,” etc. (6:18) What is asked of us here?

. Have our ancestors ever attempted to test Hashem? If yes, when? Why mention it here?

. “If your son shall ask you,” etc. Which son (of the ’four sons’) is written about here?

. What answer is given here? Is it the same as in the Haggadah?

. Give three prohibitions about idol worship mentioned in the beginning of Chapter 7.

. *Hard question:* Prove that a son of a Jewish mother and a non-Jewish father is considered Jewish, but not a son of a non-Jewish mother and Jewish father.

. Explain the differences: [.verse]#mizbeyach#{ltr}, [.verse]#matzeivo#{ltr}, [.verse]#ashairo#{ltr}, [.verse]#pesilim#{ltr}. (See <<posuk>> 7:6.)

. “Not because of your greatness (in population),” etc. What different traits of Jews and non-Jews are described here (according to the Midrash)? Examples?

. Which two categories of <<tzadikim>> are mentioned in <<posuk>> 7:9?

. How is His reward different for the above two kinds? Proof?

. His enemies also get rewarded. Why? Is it good for them?

. Twice in the parsha is the word <<hayom>> (today) emphasized (“That I command you *today*”). What are the two messages here?

. What is the special name and mood for this <<Shabbos>>?

. What special day occurs right in the middle of Av (its name, history and observance)?
