[#foreword]
[preface]
== Foreword
Anyone who has ever been a student at Yeshivas Tiferes Bachurim knows that one of the regular features of the yeshiva <<seder>> was Rabbi Wichnin’s Chumash questions. Weekly he would stand at the <<bimah>> at the center of the <<beis medrash>>, and with wit and wisdom review the timely Torah portion, using a series of penetrating questions he developed over the years. Whether these ‘parsha sheets’ contained nineteen or ninety-nine questions, each student was required to complete them on his own time outside his already rigorous schedule. During his weekly review, no student was exempt from being called upon by name to answer at least one of the questions. Even though Rabbi Wichnin demanded unambiguous and thorough answers, he was nevertheless gifted at making his students comfortable.

While still a student in yeshiva, I realized the value of these questions and gathered the well-worn, xeroxed parsha sheets, collected over the years, and presented to Rabbi Wichnin the idea of printing them in book form. Such a workbook would be made available to each yeshiva student in order that he would have year’s worth of parsha sheets at his fingertips, rather than collect them on a weekly basis.

Rabbi Wichnin explained that the idea was not a novel one, but that no one had ever taken the initiative to carry it out. Without hesitation, the original questions were re-typed and the process of producing a workbook was set in motion. Rabbi Wichnin agreed to write the questions on the three parshas <<Bereishis>>, [.verse]#Haazenu#{ltr} and <<Vezos-Habracha>>. (Since the yeshiva seder was not in session during the <<yomim-tovim>>, questions had not been written for these three parshahs.) Unfortunately, Rabbi Wichnin never had the opportunity to write the three missing parsha sheets, nor to edit this book.

Now more than ever, Rabbi Wichnin’s students and former students are eager to have their beloved teacher’s Chumash questions in hand once again. With the help of the alumni of Yeshivas Tiferes Bachurim, members of the Morristown community, friends, family and colleagues, Rabbi Wichnin’s serious educational work has been transformed from the humble handouts into this handy workbook.

It is our hope that questions from the missing parshios, modeled after Rabbi Wichnin’s distinctive style — along with a book of answers — will be written and
published for the world to benefit from. In the meantime, this workbook has been prepared especially for the 26th of Av, to honor Rabbi Wichnin on the day of his <<shloshim>>.

May the learning that comes forth from this book bring an <<aliyah>> for Rabbi Wichnin’s <<neshamah>>, and may our increased learning merit us all to see <<techiyas-hameisim>>, and the <<hisgalus>> of <<melech-ha-moshiach>>, when we will once again learn from our Rebbe, as well as from our beloved teacher and Rosh Yeshiva, Rabbi Wichnin. May it happen <<teichef-umiyad-mamash>> — speedily and in our days!

Yosef Chaim Lester

26 Menachem Av 5755

Morristown, NJ

