[#bereishis]
== Bereishis

These questions for parshas Bereishis (which were found in handwritten form) were discovered while _The Chumash Questions_ was in the process of being printed. It is quite clear that they are incomplete and, therefore, it is also possible that they are a first draft. Nevertheless, they are a valuable addition to the book, and have been included as an insert, in the absence of anything more authoritative.

. According to Rabbi Yitzchok, which way should the Torah have started? Why?

. And why did the Torah start with the story of creation?

. Prove that the Torah does not teach us the order of creation.

. How did our sages explain the meaning of Bereishis?

. Which physical elements were definitely created before Heaven and Earth?

. How did the actual creation ‘change’ from the original plan (because the world couldn’t cope with it)? Proof?

. Is darkness a creation or is it only the absence of light? Proof?

. What was hovering on the water?

. How was the light created?

. Why was a separation made between light and darkness? (Two reasons.)

. Why does it say “one day” instead of “the first day”?

. According to Rashi, when were the angels created?

. Was the sky created on the first day or the second day?

. How did the upper waters remain standing in their place?

. Why is “ki tov” not mentioned on the second day but mentioned twice on the third?

. Why is heaven called shamayim? (Three reasons.)

. If all the seas are really one body of water, why are they called “seas,” in plural, instead of “sea,” in the singular?

. The earth didn’t produce the trees properly. Explain.

. Was the earth ever punished? Explain.
