[#chayei-sara]
== Chayei Sara

. Why is the word <<shonoh>> (year) repeated in the first <<posuk>>?

. Did Sara have a good life? What about the troubles?

. Why was Hebron called <<kiryas-arba>> (City of Four)? Is there a city by this name today? Where?

. Why is Sara’s death mentioned right after the <<akeidah>>?

. When Avrohom says, “I am a newcomer and an old settler,” What does he mean? (See <<posuk>> 4.)

. Why was the <<meoros-hamachpeila>> called by this name?

. What was special about Efron? Was he a nice person?

. How does the Torah hint to us about Efron’s character?

. Did Avrohom’s work make a difference in Hashem’s Kingship?

. What did Avrohom ask from Eliezer? Why was it necessary (in your opinion)?

. What did Avrohom warn him about? What question did Eliezer ask Avrohom about it?

. Why didn’t Avrohom want Yitzchak to marry a girl from the local population (the people of Cnaan)?

. How were Avrohom’s camels recognizable in the street?

. Eliezer had “all his master’s riches *in his hand*.” How?

. What kind of <<midoh>> (trait) was the girl supposed to have? Why?

. How did Eliezer recognize that Rivkah was a special person (even before he spoke to her)?

. In what way did Rivkah offer to give more than she was asked?

. What was symbolized by the jewelry that Eliezer gave her? (Check the numbers.)

. Why did he ask her who she was *after* giving her the gifts?

. What did Eliezer do and say after Rivkah invited him to the house?

. Why did Lavan run so fast to greet Eliezer?

. Did Eliezer have any personal plans for Yitzchak? Proof?

. Why did Avrohom reject these plans?

. How do we know that Eliezer had <<kfitzas haderech>> (a miracle to quicken his trip) and why was it necessary (in your opinion)?

. How do we know that the talk and stories of the <<Avos>> and their servants are more precious than our Torah learning?

. How many times is Eliezer’s story repeated in the parsha? Do you notice any changes in the recounting?

. How do we know that even non-Jews believed that a <<shidduch>> (match) is <<bashert>> (predestined)?

. How can we tell that Rivkah’s brother was a <<rasha>> (sinner)?

. How do we know that one must thank Hashem for good news?

. What happened to Besueil? How do we know?

. From where do we learn that a woman must be asked whether she consents to a marriage and cannot be forced into it by her parents?

. What ‘daring’ answer did Rivkah give to her family?

. What was Yitzchak doing when Rivkah arrived?

. What were the special miracles and blessings that Sara had in her tent? Did Rivkah have them? Proof?

. What kind of *special gift* did Yitzchak get from his father?

. What *strange gift* did the other children get?

. Why is the word <<shonoh>> repeated in connection with Avrohom’s passing?

. How do we know that Yishmael did <<teshuvah>> (repented)?

. Why was Avrohom afraid to bless Yitzchak? What did Hashem do?

. Which mitzvoh did Hashem do after Avrohom’s passing?

. Where is <<Minchah>> (afternoon) davening mentioned in this parsha?

. In this parsha there is a special hint to one of Rebbe’s main <<mivtzoyim>>. Where?
