[#noach]
== Noach

. Why are Noach’s qualities, instead of his sons’ names, mentioned in the first <<posuk>>?

. “In his generations,” etc. (<<posuk>> 1) What is the dispute among <<Chazal>> (our Sages) about this?

. How does Noach compare to Avrohom’s greatness? Proof?

. What were the three major sins of the generation of the flood?

. Did good people also suffer in the flood? Proof? Reason?

. Which sin caused their final verdict to be sealed against them? Proof?

. For how many years did Noach build the <<taiva>> (ark/box)? Why was *this* safety method used?

. How was Moshe’s <<taiva>> built differently than Noach’s? Why?

. What were the dimensions of the <<taiva>>? How many floors were there? Their uses?

. Why was its roof made narrow? Why was its door on its side?

. How did they get light into the <<taiva>>? (Two opinions.)

. In punishing the human race, Hashem partly agreed with advice of long ago. Explain.

. What are the three meanings of the word <<mabul>>? Why was a *covenant* necessary?

. Since many of the animals became perverted, how did Noach know whom to admit?

. Were there any species of animals that were not saved? Which kind of species came in pairs?

. Prove that in the presence of a person we do not praise his good qualities too highly. Why? And in his absence? Proof?

. Prove that Noach studied and knew Torah. How about Avrohom?

. Why did Noach take in seven pairs of kosher animals, but only *one* pair of others?

. It does not mention whether the seven pairs of birds were kosher ones. Were they? Proof?

. Why was there an additional wait of seven days (+120 years) before the <<mabul>> started?

. How many days did it rain? Why that number?

. In <<pesukim>> 6:22 *and* 7:5 it says, “And Noach did,” etc. Why the repetition?

. Why were the men and women prohibited from cohabitation in the <<taiva>>?

. How old was Noach when the <<mabul>> started? And his sons? (Check Bereishis 5:32.)

. Was Noach absolutely certain in his belief that the <<mabul>> would come? Proof?

. The <<mabul>> started in the *second* month. Which month was it, according to the Sages?

. First it says the *<<mabul>>* came, and later it says the *rain* came. How do we resolve this?

. Why was it necessary to state, “In the *midst* of that day Noach came in,” etc?

. Many people were killed (*not* drowned) right after Noach entered the <<taiva>>. Why?

. How deep was the <<taiva>> in the water when it was carried by the <<mabul>>?

. The waters went higher than the tallest mountains. How much higher?

. Which living species were safe even though they weren’t in the <<taiva>>? Proof? Why?

. In what kind of health condition did Noach survive?
Why?

. Why is Hashem’s Name of Judgment mentioned in connection with stopping the <<mabul>>?

. Was Noach doing anything to stop the <<mabul>> while he was inside?

. When Hashem decided to destroy this generation, His Name of Mercy is used. Why?

. Which merits of the animal inhabitants of the <<taiva>> did Hashem remember?

. Why doesn’t it say, “*all* the springs closed up,” as it says at the opening of the parsha?

. If the <<taiva>>’s ‘Window’ was a precious stone, what does it mean that “Noach opened the window” (to send out the birds)?

. The raven didn’t go where Noach sent him. Where *did* he go? Why?

. It says that the raven had another destination later in history. Which?

. The dove (<<yona>>) was sent out many times. How many? What happened each time?

. What was the symbol of the olive leaves in the dove’s mouth?

. How long did the whole <<mabul>> experience last?

. In which month did the water dry? When did the *earth* dry completely?

. In what way can it be said that the <<taiva>> was a foretaste of <<Moshiach>>'s times?

. What behavior were the animals committed to after leaving the <<taiva>>?

. From which kinds of animals and birds did Noach take <<korbanos>> (sacrifices)? (See 8:19.)

. How did Noach know that he had to bring <<korbanos>>?

. What promise did Hashem make after Noach’s <<korbanos>>?

. What reason did He give for His promise? (See 6:5.)

. When does a person get his <<yetzer-horah>> (evil inclination)? Explain.

. In the haftorah of this parsha, it says that Hashem made an oath for the future. Where is this hinted here?

. Into how many seasons is the year divided here? Which months are included in each?

. How were the seasons affected during the period of the <<mabul>>?

. What kind of power was given to the human beings over the animals?

. What new kind of food was the new generation allowed to eat? Why?

. What kind of meat and blood were nevertheless forbidden to them? Why?

. The taking of human life became forbidden to *all*. Explain.

. When is a murderer punished by a human court and when by Hashem?

. Why is it forbidden to destroy human life but not animal life?

. It is said that we have a reference here to the punishment of <<olom-haboh>> (the World to Come). Explain.

. “Be fruitful and multiply,” etc. This was already said to Adam; why the repetition?

. Noach was still worried. Why? What assurance did he get now?

. What does the rainbow symbolize? Did all generations need it? Why?

. If everything was destroyed, how was Noach able to plant a vineyard?

. The planting of this vineyard was a mistake. Why? Who else sinned with wine?

. Noach’s three sons behaved quite differently during their father’s trouble. Explain.

. What special reward did Shem get? Why? And Yefes?

. What was the curse that Noach put on Cnaan? Why?

. What is hinted here about the difference between the first and second <<beis-hamikdash>> (Sanctuary)?

. Who was Nimrod? What were his activities? How did Ashur react to them?

. There was a prophet in those days called Eiver. What was his prophecy?

. “They spoke one language.” Which? “They had one idea.” What are the opinions about this?

. “And Hashem came down to see,” etc. What lesson is given here to human judges?

. “The sons of Adam” (11:5). Why are they connected here to Adam?

. What was the punishment of the <<dor-haflaga>> (generation of dispersion)?

. That generation, unlike the generation of the <<mabul>>, has lost their share in <<olom-haboh>>. What great lesson do we learn here about peace and harmony?

. How did Terach cause the death of his son Horon?

. What was the difference between Avrohom’s faith and that of Horon?

. Sara was called <<Yiska>>. What are the various meanings of this name?

. “And Terach died in Choron.” Did he actually die at this time? Explain.

. Until Avrohom there was Hashem’s anger in the world. And with Avrohom?