[#beshalach]
== Beshalach

. Why were the Jews taken out through a *distant* route after leaving <<Mitzrayim>>?

. Yoseif’s ‘ark’ (his remains) was taken out by *Moshe*. Why?

. How did the Jews get weapons in the desert? How many Jews remained in <<Mitzrayim>>?

. Why didn’t Yoseif tell his own children to carry him to Eretz Yisroel?

. What was the purpose of the commandment, “Let them return and rest. . . in front of Baal Tzfon”?

. How is Hashem’s honor increased? What compliment is given to the Jews here?

. How did Paroh find out that the Jews left for good?

. Why do we say the <<shira>> (song) ‘Az Yashir’ on <<shvi-i-shel-pesach>> (the seventh day of Pesach)?

. How did Paroh convince his people to join him in pursuing the Jews?

. What is the basis for the statement, “The best <<Mitzri>> (Egyptian) should be killed”?

. Where is there a hint that the Jewish nation was following the Ramah (Reb Moshe Isserles) in <<halacha>> (Jewish law)?

. It is said that the Rashbi, the Ari, and the Baal Shem Tov’s teachings will bring <<Moshiach>>. Where is this hinted in the <<parsha>>?

. What did the Jews say to Moshe when they noticed the Egyptians coming toward them? What did Moshe answer them?

. What is the real Jewish way to respond in the face of trouble? Why?

. Which merits caused the splitting of the sea before the Jews?

. What kind of judgment was held over the Jews at that time? Proof?

. How does the <<mashal>> (example) of a father and his son explain what happened near <<yam-suf>> (the Red Sea)?

. How were the Jews assured that the Egyptians were not coming out on the other side (of the sea)?

. Where is there a hint about <<techiyas-hameisim>> (resurrection of the dead) in the <<shira>>?

. In what ways were the Jews at the Red Sea superior to the <<Nevi-im>> (Prophets)?

. There were three kinds of Egyptian people and they were punished differently at the sea. How?

. The word [.verse]#yemincha#{ltr} is mentioned several times in the <<shira>>. What is said about it?

. Why is Miriam called <<Neviah>> (Prophetess)? And why ‘sister of Aharon’?

. Why did Moshe have to force the people to ‘move on’ after <<krias-yam-suf>> (the parting of the Red Sea)?

. Which mitzvos were given in Marah? And which tests?

. If the diseases of the Egyptians were not to be put upon us, why does it say that Hashem will *heal* us?

. In what connection are the numbers 12 and 70 mentioned?

. How long did their food leftovers (from <<Mitzrayim>>) last? When did the <<mon>> (manna) come?

. <<Bnei Yisroel>> (the Children of Israel) asked for bread and meat. How was it given to them? Why?

. In what ways did the <<mon>> test <<bnei-yisroel>>? What happened on <<Shabbos>>? Which <<halacha>> comes from it?

. According to our Sages, getting a <<shidduch>> (marriage partner) and getting
    <<parnasah>> (livelihood) are likened to <<krias-yam-suf>>. Why?

. In which places in the davening is <<krias-yam-suf>> mentioned?

. The <<mon>> was described as lying in a box. Explain why.

. What scientific experiment does Rashi suggest in connection with <<mon>>?

. What ‘big miracle’ happened concerning the amount of the <<mon>>?

. How did the nations of the world find out about the taste of <<mon>>?

. Did the <<mon>> come down on Yom Tov? Source?

. Why was Moshe told to put away a jar of man for remembrance?

. When did the <<mon>> stop? How many years did it come?

. Why is the story of Amalek written here?

. Who was Chur? Kalev? Why is Chur mentioned here?

. What did Moshe do at the time of battle to confuse Amalek?

. What was Yehoshua told to do to Amalek in the future?
