[#bo]
== Bo

. “Come to Paroh,” etc. For what purpose?

. If Hashem hardened Paroh’s heart, why does Paroh deserve punishment?

. What was the purpose of the <<makos>> if Paroh would refuse anyway?

. What was the <<arbeh>> (locusts) supposed to do to the land of <<Mitzrayim>>?

. Where is there a hint in the first <<posuk>> that three <<makos>> will come? (See Baal Haturim.)

. What did Paroh’s servants say to him when they heard about the locusts?

. How did Paroh want to compromise upon hearing about the locusts?

. What *historic* description is given to arbeh?

. A similar description is given to another locust attack. Which was greater?

. According to the Midrash, how did Moshe’s prayers help to change the astrologers’ prediction?

. How was the removal of the locusts different from the removal of the frogs?

. What was the difference between the first and last three days of darkness?

. How was Paroh willing to compromise after being hit with darkness? What was Moshe’s answer?

. What two important purposes were served by the <<makah>> of darkness?

. What warning did Paroh give to Moshe after the darkness? What did Moshe answer?

. Why did Hashem *insist* that Moshe ask the people to get the ‘good things’ from the Egyptians?

. When was Moshe told about the last <<makah>> (<<makas-bechoros>>, slaying of the firstborn)? Proof?

. Why did Moshe say ‘around midnight’ while Hashem said ‘at midnight’?

. Why did the tenth plague of the firstborn affect the captives? The slaves? The cattle?

. Prove that despite everything, Paroh *was* accorded his respects by Moshe.

. Where did Hashem speak to Moshe about the <<korban-pesach>> (Passover sacrifice)?

. What was Moshe told about Rosh Chodesh? About the month of Nissan?

. In which part of the day did Hashem speak to Moshe? What difficulty did Moshe have?

. Why were they told only this one time to take the lamb four days before its sacrifice?

. When is the <<korban-pesach>> brought? Who may eat from it? Who may not?

. Why is the <<korban>> called <<Pesach>>? On which side of the door was the blood put? Proof?

. On which days of <<Pesach>> is the eating of <<matzo>> (unleavened bread) *voluntary*? Proof?

. What is the punishment for eating <<chametz>> (leaven)?

. What may be done on Yom Tov which may not be done on <<Shabbos>>? Source?

. Of the ‘four sons,’ whose questions and answers are mentioned in our parsha? Where?

. “The Jews dwelt... 430 years!” But they were in <<Mitzrayim>> only 210 years? Explain.

. Which other mitzvos (connected with <<yetzias-mitzmyim>>, the exodus from Egypt) are mentioned in the two
<<parshiyos>> of tefillin (<<Kadaish>>, <<Vehaya>>) at the end of this <<sedra>> (parsha)?
