[#ki-sissa]
== Ki Sissa

. Why weren’t the Jews counted directly? Were they ever counted directly?

. What <<halacha>> about counting people do we learn from the second <<posuk>>?

. How was Moshe shown the half-Shekel? What else was he shown in this way?

. How many <<zuzim>> in a Shekel? How many <<geira>> in a zuz?

. Why is the word <<terumah-term>> mentioned three times?

. How did they spend the silver from the two counts?

. Why was the count exactly the same both times? Was there a miracle in it?

. What was the <<kiyor>>? Who used it? For what?

. Which <<halacha>> is derived from the parsha of <<kiyor>>?

. What did the oil contain besides the olive oil?

. What was this oil used for? What are the opinions of Rabbi Yehuda and Rabbi Meir on the preparation of this oil?

. What was the weight of the aromatic herbs? The measure of the oil?

. “Anything touching *them* should become *holy*.” Touching whom? Holy for
what?

. Our Sages said that all of the oil remained intact. How do we know?

. What are the two prohibitions about the oil? Punishment for transgressing?

. How many herbs were used for the <<ketores>> (incense)? How many are mentioned?

. One of the herbs didn’t have a good aroma. Which? What do we learn from this fact?

. Into how many portions was it divided? Why? What about the extras?

. How does Rashi explain <<chochma>>, <<tevuna>>, <<daas>>? Is this similar to the explanation given in Tanya for <<chochma>>, <<binah>>, <<daas>>? How?

. Why is the subject of <<Shabbos>> mentioned here?

. <<Shabbos>> is a sign between Hashem and the Jews. How?

. For whom is this sign intended? Purpose?

. What are the punishments for desecrating the <<Shabbos>>? <<beshogeig>>, <<bemeizid>>, <<behasraah>>?

. Why is <<Shabbos>> called <<shabbos-shabbaton>>? What else is called by this title?

. Prove that the Torah is not necessarily arranged in chronological order.

. What wording is used in the Hebrew version of the above rule?

. Why is the Torah likened to a <<kallah>>? (Two reasons.)

. How was it possible for Moshe to learn the whole Torah in such a short time?

. How did the people mistakenly decide that Moshe was late in his return?

. Which two things did the <<Satan>> do to confuse the people?

. Prove that they only asked for a leader to substitute for Moshe, not for a deity.

. Why did Aharon decide to ask for the *women’s* and *children’s* jewelry?

. Who actually donated the jewelry? Proof?

. After Aharon threw the gold into the fire, *who* produced the <<egel-hazahav>> (golden calf)? (Two opinions.)

. Prove that the mixed multitude of <<erev-rav>> (Egyptian converts) started the whole thing.

. Why did Aharon feel forced to announce a celebration for them? Why for the *next* day?

. Why didn’t he ask them to build the altar instead of building it himself?

. What happened to Chur? Why? How was he related to Aharon?

. Why was it so easy for them to get up early the next morning? Did they awaken so quickly for <<matan-torah>>? What can we learn from it?

. What kind of <<mussar>> did Moshe get from the Heavenly Court?

. Why does it say “*Your* nation sinned” rather than “*the* nation”?

. Why were the Jews called a stiff-necked people?

. How did Moshe get the hint that prayer might still help?

. What reason did Moshe give to Hashem not to be angry at them?

. Why did he mention here the three Patriarchs?

. How did Hashem respond to Moshe’s prayers?

. On which days do we read Moshe’s prayer in the Torah? Why?

. “They (the tablets) are the doings of Hashem.” Give two interpretations for this.

. When Yehoshua said, “Hear a sound of war in the camp,” what did Moshe answer?

. What reason did Moshe have (from a <<halacha>>) to break the <<Luchos>> (tablets)?

. Why did Moshe give the people to drink from the water (with the gold-dust of the golden calf)?

. Three different punishments were given there for three different groups. How?

. What did Aharon answer when Moshe asked him about the egel?

. Did any of the Levi’im participate in the <<chet-ha-egel>> (sin of the calf)? Proof?

. What did Moshe command the Levi’im to do? Why was it so difficult for the Levi’im?

. Moshe’s prayer was already accepted (see 32:14); why did he have to plead for them again? (see 32:30.)

. What explanation (or cause) did Moshe offer to Hashem for this great sin?

. In the parable in Rashi for above why does it say that “He gave him food and drink” (i.e., the father gave to the son)?

. Moshe said, “Erase me from Your book.” Why? What did Hashem answer?

. How did Hashem make the nation’s punishment easier? Why was He sending an angel with them?

. “*Go up* from here.” (33:1) Why is ‘up’ used here? (Two reasons.)

. Why are only *six* nations mentioned here? Who was the seventh? Where was he?

. What reason did Hashem give for not wanting to lead them?

. “And the people heard *this bad thing*,” etc. (33:4) Which thing? How did they react?

. How long does Hashem’s anger last? Who tried to use it against the Jews?

. What immediate punishment did they get?

. Why did Moshe remove his tent from the camp? How far did he move?

. What name did Moshe give his tent? Who usually came to see him there?

. Who else, besides the Jewish people, came to see Moshe? Proof?

. What did the people do when seeing Moshe leave the camp? Any parallel today?

. What did the people do *after* Moshe arrived at his tent? Why?

. During which period did Moshe hear Hashem’s voice at *his* tent? Why not afterwards?

. “And he returned to the camp.” (33:11) Why did he have to *return*? (Two reasons.)

. What did Moshe request in <<pesukim>> 33:12-13? What was the response?

. What did Moshe request after the first response of Hashem? What else did Moshe ask? What was the response?

. Then Moshe asked another favor. What? What was the answer to him?

. What did Moshe learn from this answer? Do we use it? When?

. What special promise did Moshe get concerning the 13 Attributes of Mercy?

. What was the reason given why Moshe couldn’t see all he wanted to see?

. Is Hashem in the world or is the world in Hashem? What Name of Hashem tells us this?

. From what Moshe saw we learn that Hashem ‘puts on tefillin.’ How?

. How did Moshe get rich? How were the second <<Luchos>> different than the first?

. In the <<mashal>> that Rashi brings (34:1), who are the maids? Who is the bride?

. How was the *giving* of the second <<Luchos>> different than the giving of the first? Why? What kind of proper behavior do we derive from here?

. Why is Hashem mentioned twice in the 13 Attributes of Mercy? Explain. Why the need for mercy before the sin?

. Explain the following (two meanings): _notzer chesed la’alafim; noseh avon vafesha; vechatah; venakeh; lo yenakeh_.

. Prove that the <<midoh-tovah>> is *500 times* greater than the <<midoh-poranius>>.

. When do children get punished for the parents’ sins?

. After Moshe heard the 13 Attributes of Mercy, what request did he make? What was the response?

. Why is eating from the idol sacrifices considered so terrible?

. Why is there a commandment to chop of the head of a firstborn donkey (sometimes)?

. “They shouldn’t come empty handed to see me.” (34:20) What are the two meanings here?

. “And you shall rest from plowing and harvesting.” What does this teach us about <<Shabbos>>? What other interpretation is there concerning the laws of the seventh year (Shmittah)?

. Why are some prohibitions (and mitzvos) repeated several times in the Torah?

. What promise is given to those who go up to the <<beis-hamikdash>> for the holidays (<<yom-tov-aliyas-haregel>>)?

. Prove that chicken with milk is not prohibited from the Torah.

. How do we know that it’s forbidden to write down <<torah-shebe-al-peh>> (Oral Law)? Then why do we have Mishna, Gemora, <<shulchon-oruch>>?

. How do we see the strong destructive power of sin? Where did Moshe get his holy light rays?

. Why did Moshe use a mask? How did he teach the Torah to the Jewish people?


[discrete]
==== Extra
[start=100]
. When else do we read the first part of this parsha?

. When do we recite the <<pesukim>> of <<veshomru>> (31:16)?

. When do we read (from the Torah) <<pesukim>> 34:1-10? Why?

. When do we read <<pesukim>> 33:12-34:10?

. How many mitzvos are written in this <<parsha>>, positive and negative?

. Why didn’t Yehoshua know what was going on at the camp?

. Which <<yomim-tovim>> (holidays) are *not* mentioned in this <<parsha>>? Why?
