[#terumah]
== Terumah

. Which items of the <<Mishkan>> (Tabernacle) are described in this parsha?

. How many items (materials) were needed for the building of the <<Mishkan>>?

. Three different types of contributions are hinted at in the first <<posuk>>. Find the hints and describe the contributions.

. A number of precious metals are mentioned. Which one had to be contributed in equal amounts by all?

. The wool they used had to be of various colors. Which?

. They used two (or three) types of animal skins. Of which animals?

. Which item was available (by a miracle) only then and is no more?

. What was the oil used for? The spices (<<besomim>>)? The precious stones?

. How did they get <<sheetim>> (cedar) wood in the desert?

. In <<posuk>> 9 why does it say “and so you shall do” after saying it in posuk 8? Were the <<keilim>> (utensils) in the first <<beis-hamikdash>> similar to those in the <<Mishkan>>? Why?

. Why does it say in <<posuk>> 8, “And I shall dwell *in them*,” rather than in *it*?

. How was the <<aron>> (ark) ‘covered’ with gold inside and outside? What were its dimensions? Which <<neis>> (miracle) is related to its space?

. Why was there a ‘crown’ made on top of the <<aron>>?

. What other parts did the <<aron>> have besides the ‘boxes’ and the ‘crown’?

. What were these: [.verse]#taba'os#{ltr}, [.verse]#badim#{ltr}, [.verse]#eidus#{ltr}, [.verse]#kapores#{ltr}, [.verse]#za'ir#{ltr}, [.verse]#tzalos#{ltr}?

. How many [.verse]#keruvim#{ltr} were there? How were they made? What kind of ‘face’ did they have? Where were the [.verse]#keruvim#{ltr} located?

. “And I shall speak to you from on top of the <<kapores>>.” Where did the Voice really come from and where did Moshe hear it?

. The [.verse]#shulchon#{ltr} (table) also had a ‘crown.’ Why? Where was it placed?

. What other parts did the [.verse]#shulchon#{ltr} have? What food was on it?

. Why is the bread called [.verse]#lechem *hapanim*#{ltr}? Who ate it? When?

. Why does it say the <<menorah>> *should be made* rather than *you shall make it*?

. How many candlesticks did the <<menorah>> have? How many other parts? How tall was it? Which kind of tools served the menorah?

. Where was Moshe shown the works of the <<Mishkan>>?

. How many curtains did the <<Mishkan>> have? What were their dimensions?

. What was the roof of the <<Mishkan>> made of? Dimensions?

. How many boards ([.verse]#kerashim#{ltr}) did they use? Dimensions of each [.verse]#keresh#{ltr}?

. What were the [.verse]#adonim#{ltr}? What were they used for? How many were there? Which donations went into the making of the [.verse]#adonim#{ltr}?

. What were the [.verse]#brichim#{ltr}, [.verse]#tabaas#{ltr}, [.verse]#yados#{ltr}?

. What was the [.verse]#paroches#{ltr}? What was it used for? Dimensions?

. What was the name of the [.verse]#paroches#{ltr} in the (first) <<beis-hamikdash>>? Dimensions?

. Where was each of these placed: [.verse]#shulchon#{ltr}, [.verse]#menorah#{ltr}, [.verse]#aron#{ltr}?

. The Gemora says that if one wants to pray for wisdom he should turn southward, and for riches, northward. Can you find a reason for it here?

. What was the <<mizbeyach>> made from? Its dimensions?

. What other <<keilim>> belonged to the <<mizbeyach>>? What were they made of? Which part of the <<mizbeyach>> was similar (by name and purpose) to the <<aron>> and <<shulchon>>?

. How big was the [.verse]#chatzeir#{ltr} (courtyard) of the <<Mishkan>>? And its curtains?

. What was the purpose of the [.verse]#masach#{ltr} for the <<Mishkan>> and the one for the [.verse]#chatzeir#{ltr}? Their dimensions?

. Is there a mitzvoh that still applies in our times (also) that we learn from this parsha?

. Define and state the purpose of these:
[upperalpha]
.. [.verse]#Vovim#
.. [.verse]#Amudim#
.. [.verse]#Siros#
.. [.verse]#ya'im#
.. [.verse]#Mizrkos#
.. [.verse]#Mizlgos#
.. [.verse]#Machtos#
.. [.verse]#Michbar#
.. [.verse]#Karkov#
.. [.verse]#Reshes#
.. [.verse]#Kilayim#
.. [.verse]#Kronos#
.. [.verse]#Yeseidos#
.. [.verse]#Krosim#
.. [.verse]#Lulaos#
.. [.verse]#Malkochos#
.. [.verse]#Kaftorim#
.. [.verse]#Konim#
.. [.verse]#Gviyim#
.. [.verse]#Prachim#
.. [.verse]#Ke'oros#
.. [.verse]#Kapos#
.. [.verse]#Ksavos#
.. [.verse]#Menakiyos#
.. [.verse]#Misgeres#
.. [.verse]#za'ir#
.. [.verse]#Kenafayim#

. There are five (or six) <<pesukim>> in the Torah which contain a word that could be read with the first half *or* with the second half of the <<posuk>>. These doubts have not been resolved. This <<parsha>> has one of these <<pesukim>>. Which is it?

