[#yisro]
== Yisro

. “And Yisro heard,” etc. What exactly did he hear?

. What were Yisro’s other (six) names? Reasons? (Give three.)

. Why was Moshe’s family in Midyan, and not in <<Mitzrayim>>?

. What were the reasons for the names Gershom and Eliezer?

. Did Paroh ever attempt to use a sword against Moshe? What happened?

. Why is it emphasized that Yisro came to the *<<midbar>>* (desert)?

. Did Yisro arrive before or after <<matan-torah>> (the Giving of the Torah)? Proof?

. Was Yisro happy to hear about the downfall of the Egyptians? Proof?

. What’s a famous saying about [.verse]#geirim#{ltr} (converts)?

. Only a person like Yisro could have made such a statement about faith. Which statement?

. Aharon, the elders and Yisro were eating together. Where was Moshe?

. What is the proof that the part about judges does not appear in chronological order?

. What was bothering Yisro about Moshe’s system of justice?

. Which qualities did Yisro require for judges to have?

. On which day did they arrive at <<har-sinai>> (Mount Sinai)? What mood were they in?

. Why is Hashem’s care of <<bnei-yisroel>> compared to the way an eagle cares for his young?

. ‘All beginnings are hard.’ Where in the parsha is this idea applicable?

. “You shall be unto Me a nation of priests.” But <<Kohanim>> came from only one tribe? Explain.

. Prove that all of the blind (and the deaf, etc.) were healed.

. Did Moshe add an extra day of preparation on his own?

. The Jewish nation was (and is) compared to a *disciple* and to a *bride*. Where?

. Did Hashem speak from Heaven or from <<har-sinai>>? Explain.

. “And the <<Kohanim>> and the people shouldn’t go up,” etc. Were there ‘Kohanim’ then?

. What was unusual about Moshe’s voice when he was saying the eight commandments to the nation?

. Were Moshe, Aharon, and the ‘<<Kohanim>>’ standing together? Explain.

. How did the people respond to each commandment?

. Why did Hashem begin by saying “I ... am the *One Who took you out from <<Mitzrayim>>*”? (Three reasons.)

. Why are the idols called ‘other’ deities? How does the Tanya explain it? (See Ch. 22.)

. Prove that Hashem’s good measure is 500 times greater than His harsh measure.

. In the <<aseres-hadibros>> (Ten Commandments), where do we apply the twelfth method of interpretation that is taught by Rabbi Yishmael?

. Why can’t we use iron in the building of the <<mizbeyach>> (altar)?

. Why is <<matan-torah>> a greater experience than all other miracles?

. When else do we read (most of) parshas Yisro other than on <<Shabbos>>?

. Find an *obvious* connection between the parsha and the portions of Tanya that we often learn this same week.

. Why were such “simple” instructions chosen to be included in the 10 commandments?

. In which way were the Bnai Yisroel compared to Yisro at Mattan Torah?

. On which day of the week was the Torah given? How do we mention it on that day?
