[#tetzaveh]
=== Tetzaveh

. What commandment is given in the first posuk?

. Which process was used to extract the olive oil for the menorah?

. Which oil was kosher for a <<Korban Minchah>> but not for the menorah? Why?

. How is the word <<tamid>> (steadily) interpreted in the halachos of the menorah differently than in the halachos of the <<lechem hapanim>> (showbread)?

. How much oil was poured into the menorah every night? Why?

. How many garments did the <<Kohein Gadol>> (High Priest) wear? Which?

. What were the five materials from which the garments were made?

. What were the special garments of <<choshen>> and <<eifod>>?

. What does the word <<kehuna>> (or Kohein) mean?

. What was inscribed on the two <<shoham>> stones? What for?

. How many *letters* were inscribed in each stone?

. In which way did one of the names on these stones differ from the regular count? In which *order* were they listed?

. Which three names of tribes did *not* appear on these stones? Why?

. Why is the <<choshen *hamishpot*>> called by that name? (Two reasons.)

. What kind of precious stones were installed in the choshen hamishpot?

. What were the <<urim v’tumim>>? Where were they inserted?

. In the second Beis Hamikdash did they have the choshen? Complete? What other differences were there in the keilim of the second?

. What was attached to the choshen that caused Aharon to announce his arrival? What lesson in good manners could be learned from it?

. What was the <<tzitz>>? Who wore it? When? It also has a second name. What is it? The Gemora learns out a <<din>> (law) about tefillin from the <<tzitz>>. Which?

. The tzitz brought Hashem’s forgiveness for certain sins. Which?

. There are two opinions about the meaning of <<tamid>> written in connection with the tzitz. What are they?

. How many garments did a regular Kohein wear? What were they? Did they wear a tzitz? Did they wear <<shatnez>> (mixture of wool and linen)?

. If a Kohein is missing a garment, can he serve? What if he does? What were some other prohibitions in the service of the Kohanim?

. Which korbanos were brought for the ‘inauguration’ dedication of the Kohanim? How was the <<shemen hamishcho>> used for the Kohanim?

. What were the flour offerings that were brought?

. What was the purpose of the <<par>> (ox) brought for an atonement? How was its treatment different than other kinds of <<Korban Chatos>>?

. Where is there a hint about the future death of Aharon’s two sons?

. What was done with the rams after they were slaughtered?

. What was the purpose of ‘waving’ the four sacrifices? Any resemblance to the waving of the <<lulov>> (four species)?

. Who is first in line to succeed the Kohein Gadol? What if he can’t?

. Why did the mizbeyach need atonement?

. How was the mizbeyach sanctified for service? Was oil used?

. Which animals are not kosher for korbanos? Which become <<posul>> *after* they’re brought?

. How was the ‘inner mizbeyach’ made differently than the regular mizbeyach? What was it used for?

. It is said that this parsha is the only one not to mention Hashem’s name. Why?

. In which sedra is parshas Zachor?

. Which phrase in parshas Zachor is repeated twice by the reader? How? Why?
