[#vayakhel]
=== Vayakhel

. “And Moshe gathered,” etc. On which day did this happen?

. Why was the warning about Shabbos written before other things?

. “Don’t kindle fire,” etc. Why is this <<melacha>> (work) singled out?

. Why are the commandments about the Mishkan works repeated here?

. Which roof covers are called ‘Mishkan,’ which ‘its tent,’ and which ‘its cover’?

. Why did they need *wise* people to produce the oil for the menorah?

. What was the special wisdom of the women in weaving goats’ wool?

. What did the <<nesiyim>> (heads of tribes; princes) bring? When? Why?

. Why were the nesiyim the first to bring things for the mizbeyach?

. Why is their title (nesiyim) written without the letter _yud_?

. Prove that in the presence of Hashem there is no difference between the high <<shevatim>> (tribes) and the lowest one.

. What strange announcement did Moshe command to announce in the camp?

. How many adonim and how many yados were there per keresh?

. “And Betzalel made the aron,” etc. Did he personally make it?

. The order of the Mishkan work is different here than in parshas Terumah. How?

. What special contribution did the women bring for the kiyor?

. Was Moshe happy to accept it? Why? What did Hashem say to him?

. Why was the women’s contribution used for the kiyor?

. Which items that were needed for the <<avodah>> (service) are not mentioned here?

. Which woods were covered with silver?

[discrete]
==== Extra
[start=21]
. What were the dimensions of the following: <<mizbeyach ha’olah>>, <<mizbeyach hazahav>>, <<aron>>, <<shulchon>>, <<menorah>>, <<kiyor>>?

. Why is the prohibition against fire on Shabbos mentioned here? (See Sforno, Rambam.)

. Why did Moshe have to *gather* the people *here*? (See 0hr Hachayim.)

. Why does it mention that the men came to give jewelry *with the women*? (See Sforno 2, Kli Yakar.)

. “And the Jewish community went out,” etc. Why is this mentioned here? (See Ohr Hachayim.)

. “And the nesiyim brought,” etc. Who are these nesiyim according to the Gemora?

. Was Betzalel related to Moshe? (See Rashi, Daas Zekenim.)

. “And Moshe said: Look! Hashem called the name,” etc. (35:30) Why did he say that? (See Baal Haturim, Daas Zekenim.)

. “And to *teach* He gave into his heart” etc. (35:34). Why is this emphasized? (See Ebn Ezra, Ohr Hachayim.)

. “And Betzalel made the aron.” Is that the only thing he made? (See Daas Zekenim.)

[discrete]
==== Parshas Shekalim, Rosh Chodesh Adar, etc.

[start=31]
. How many *special* parshiyos do we read between now and Pesach? What are their names?

. Why do we read parshas Shekalim on this Shabbos? Which part do we read?

. What is the source and reason for the saying, _‘Mi shenichnas Adar marbin b’simcha’_?

. How many Sifrei Torah will be used in shul this Shabbos? How many <<aliyos>>?

. In the month of Adar the Beis Din in Eretz Yisroel was concerned with <<kilayim>>. Explain.

. Certain kinds of disputes should be resolved this month. Which kind? Why?

. Why must it be *half* a shekel? Do we give it today? What did Hashem show to Moshe?

