[#behaaloscha]
== Behaaloscha

. Why is this parsha written right next to the parsha of the <<nesiyim>>?

. Rashi gives two reasons why the word <<behaaloscha-term>> is used. What are they?

. What is the meaning of the mitzvoh, “*toward the front of the <<menorah>>,*” etc? The reason for it?

. “And Aharon did so,” etc. What compliment is given to Aharon here?

. Why was Moshe *shown* a model of the <<menorah>>? Haw was it made?

. “Take the Levi’im,” etc. How was he supposed to take them?

. Why were they supposed to sprinkle special water on the Levi’im? And why did they have to shave off all of their hair?

. The Levi’im had to bring two oxen for <<korbanos>>. Why? What was unusual about it?

. Why did the whole community have to gather at the dedication of the Levi’im?

. Why is the word <<tenufah>> (lifting) mentioned here three times?

. Why are there differences in words of the <<pesukim>> in connection with the lifting?

. “Because the firstborn are Mine,” etc. How? Why is it mentioned here?

. Why is ‘<<bnei-yisroel>>’ mentioned five times in one <<posuk>> (8:19)?

. Moshe, Aharon, and the tribes participated in the dedication of the Levi’im. How?

. Different conditions *disqualify* <<Kohanim>> and Levi’im. What are these conditions?

. In one place it says that Levi’im start from age 25, in another it says from 30. Which is it?

. How long should a person study to see Whether he really has the potential? Proof?

. At the age of 50 what can a Levi do? What can’t he do?

. Prove that there is no chronological order in the Torah.

. Why didn’t this <<Chumash>> (Bamidbar) start with the subject of <<korban-pesach>>?

. Can the <<korban-pesach>> be brought on <<Shabbos>>? If most people are impure? Proof?

. When did Moshe Rabeinu tell the people about the laws of the holidays?

. What was the argument of the people who were <<tomei>> and wanted to bring the <<korban-pesach>>?

. What special praise of Moshe do we learn from the answer Moshe gave them?

. Why wasn’t this parsha about the ‘<<Pesach>> <<Sheini>>’ given by Moshe to begin with?

. What kind of people are obligated to bring the <<Pesach>> <<Sheini>>? Proof?

. Which aspects of the two kinds of <<korban-pesach>> are *like* and *unlike* each other?

. What is the punishment for totally missing the <<korban-pesach>>?

. Which other transgression of a <<mitzvoh-asei>> (positive mitzvoh) gets this punishment?

. If a person converts to Judaism after <<Pesach>>, does he bring a <<Pesach>> <<Sheini>>?

. What were the signals for the tribes to travel and to rest?

. When were the two trumpets used and when was only one used?

. How do we derive the need to recite [.verse]#malchiyos#{ltr}, [.verse]#zichronos#{ltr}, and [.verse]#shofros#{ltr}?

. How much time did the people stay at <<har-sinai>>?

. At which point was the <<Mishkan>> taken apart for travelling?

. Who travelled ahead, Gershon, Kehos, or Merori? Why?

. What was the special task of <<sheivet>> Don? Where was their position?

. What are the two opinions on the formation of the camp while travelling? Proof?

. How many names did Yisro have? Give reasons for two of them.

. What proposition did Moshe put to his father-in-law? Reason?

. What was Yisro’s reply? What were his two reasons?

. Which promises did Moshe offer to his father-in law?

. The city of Yericho had a very fertile space of 500 x 590 <<amos>>. What was decided to do with it? Who got it meanwhile? But Yisro went home?

. They travelled unusually fast this time. How fast? Why this miracle?

. Which <<aron>> kodesh travelled ahead of them? What for?

. How many clouds were with them? Proof? What purpose did they serve?

. What did Moshe say whenever they travelled? Why? Where do we recite it?

. There were two types of enemies. Which? What was Moshe’s request about them?

. Why are they called ‘Hashem’s enemies’? Why is this prayer written here?

. What number of Jews need there be for Hashem’s Presence to be among them? Proof?

. What are the people called in the Torah when they misbehave? When they are good?

. What was their complaint here? Its purpose? Who got burned for it? (Two opinions.)

. Why did they cry out to Moshe and not to Hashem? What happened to the fire?

. “Who will give us meat?” Prove that this request was not justified.

. Did they really get fish from the Egyptians for free? Why? What did they mean?

. The <<mon>> could taste like anything. Why, then, were they hungry for cucumbers, etc.?

. What was their conflict about the <<mon>>? What was the response to them?

. “Moshe heard the nation crying with their families,” etc. Why were they crying?

. What ‘complaint’ did Moshe voice to Hashem about the people? What did he request?

. “Hashem said to Moshe, ‘Gather up 70 Elders.’” But didn’t he already have 70 Elders?

. Which 70 people was Moshe looking for now? Where should he take them to? Why?

. When was Moshe compared to a woman (physical weakness)? When to a candle?

. Explain the conversation between Hashem and Moshe concerning the slaughtering of meat and the providing of fish according to Rabbi Akiva and Rabbi Shimon, and Rabbi Gamliel.

. “They said prophecy,” etc. (11:25) What are the two opinions about it (according to Rashi)?

. How did Moshe pick the 70 judges from the twelve tribes?

