[#noso]
== Noso

. Which age bracket of Levi’im were included in the count of Gershon, Kehos, Merori? Why?

. Of the above three families, which was the largest? The smallest? What were their jobs?

. There were three *general categories* of people who became <<tomei>>. What were they?

. From which camps were the above sent out? Until when?

. If a person stole, then swore falsely but later admitted his sin, how does he pay?

. This subject (stealing and swearing) is repeated here for the second time. Why?

. “And if the man has no relative,” etc. (5:8) Why must this refer to a [.verse]#ger#{ltr}?

. In <<posuk>> 5:9, [.verse]#terumah#{ltr} is mentioned but Rashi interprets this as *<<bikurim>>*.
Why?

. Which important [.verse]#din#{ltr} do we learn here about <<bikurim>>? How does that prove the rule of our sages, “the words of Torah are poor in one place and
rich in another”?

. What kind of authority does the owner (Yisroel) have on his tithes that are given away?

. One who withholds (doesn’t give) his tithes, what punishment does he get?

. And what is the reward for the one who gives his tithes generously?

. A woman who is unfaithful is being *disloyal* in a double way. How?

. Our sages said: “A person does not sin unless he is overtaken by stupidity.” Prove it from this portion.

. If this woman really committed adultery, why doesn’t she get her deserved punishment?

. Why is the flour (for her <<korban>>) made of *barley* rather than wheat?

. Prove from this parsha that it is shameful for a married woman to uncover her hair.

. What are the ingredients in the water that the <<Sotah>> drinks?

. Who else gets punished by her drinking if she is guilty?

. What happens to her through the drinking if she is innocent?

. How does one become a <<Nazir>>? What is a Nazir barred from?

. Why is the subject of <<Nazir>> written next to the portion on <<Sotah>>? Can a woman be a Nazir?

. What happens to the <<Nazir>> if he becomes <<tomei>> accidentally?

. “And he should atone on him from his *sins on the <<Nefesh>>,*” etc. What sin? (Two opinions.)

. A <<Nazir>> who concluded his period properly, what does he do at the conclusion?

. Regarding the <<birkas-kohanim>>, why is ‘saying to them’ emphasized (6:23)?

. In the first blessing there is a positive and a negative statement. What is their content?

. How is Hashem’s gift different from that of a human being?

. What is the content of the middle blessing? The third one?

. Which word appears in all three blessings? Are all of the blessings equal in length?

. Where do we say this blessing in cur prayers?

. When do <<Kohanim>> perform this mitzvoh of blessing the Jewish people? Why?

. “And I shall bless them.” Whom? (Two meanings.)

. What was the Jewish nation compared to on the day the <<Mishkan>> was erected?

. “When Moshe finished putting up the <<Mishkan>>.” But others also worked on it. Who were they? Why is only Moshe mentioned? What is the comparison with King
David?

. Those who were now the heads of tribes (<<nesiyim>>), what were they doing in <<Mitzrayim>>?

. Why were the <<nesiyim>> *the first ones* to bring their gifts to this celebration?

. Who got more wagons and oxen among the Levi’im? Why? Who got none? Why?

. What were the two possible orders by which the <<nesiyim>> could have brought their gifts? Which one was chosen?

. Find an example here to the saying of the Mishna, “One mitzvoh brings another one.”

. Who paid for these gifts, the nasi or his tribe? Proof?

. “He offered. . .he offered his <<korban>>,” etc. Why is ‘he offered’ repeated in connection with the tribe of Yissochor?

. What complaint did the tribe of Reuven have? What was ‘Moshe’s’ reply?

. What is the significance of these numbers: 930, 130, 500, 20, 7O, 10?

. Which nasi brought his <<korban>> (gift) on <<Shabbos>>? (See Baal Haturim.)

. Why is the weight of the utensils mentioned separately and also together?

. There are two <<pesukim>> that seem to be contradictory, until a third <<posuk>> comes and resolves it. Which are they?

. In what connection is the ‘Voice’ of Sinai mentioned here?

