[#introduction]
[preface]
== Introduction

_The Chumash Questions_ is a powerful tool for anyone who wants to understand the Five Books of Moses. This questions, in the form of weekly sheets on each Torah portion, were formulated by Rabbi Dovid Wichnin, o.b.m, the Rosh Yeshivah of Yeshivas Tiferes Bachurim, in Morristown, New Jersey from 1978-1995. A master teacher, Rabbi Wichnin crafted his questions to allow the yeshivah’s entire range of students, from beginners to scholars, to sharpen their Chumash comprehension skills. Over the course of nearly twenty years, thousands of students have used these questions to attain a comprehensive understanding of the written Torah by understanding the most fundamental commentary — that of Rashi.

Rabbi Shlomo Yitzchaky, better known by the acronym <<Rashi>>, lived in France from 1040-1105 and is unarguably the most widely studied Torah scholar in history. In fact, the Shulchon Oruch states that one might fulfill the requisite, “<<Shnayim mikrah v’echad targum>>” (reading the weekly portion twice, and a translation once) by reading Rashi’s commentary on the verse. Still, it is advisable to read it with the customary translation of Onkelus. Nevertheless, a G-d-fearing person will also be sure to read the Torah portion with Rashi’s commentary each week.

The commentary, which is printed in virtually every edition of the Torah, is a strict adherence to the <<pshat>> — the simple meaning of the verse. Rashi himself emphasized that his goal was to make the Torah clear to virtually every student of the Written Torah, starting with ‘<<ben chameish lemikrah>>’ — a five-year-old child who commences the study of the scripture — to the most erudite scholar who must still keep in mind that the simple meaning of the verse will always remain.

Yet the saintly Shelah, Rabbi Yeshayah Horowitz, noted that within Rashi’s commentary on Chumash are hidden the secrets of the Torah. And the first Lubavitcher Rebbe, the Alter Rebbe, called Rashi’s commentary “the wine of the Torah,” explaining that it opens the heart and reveals one’s essential love and fear of G-d.

When the Previous Rebbe, Rabbi Yosef Yitzchok Schneerson, o.b.m, instituted the <<Chitas>> — a daily schedule of Torah, Psalms, and Tanya study, he stipulated that the Torah selection must be read with Rashi’s commentary. As he explained in one of his discourses, “It is necessary to study some of the Written Torah daily with Rashi, for his commentaries are the <<terumos>> — the most select portion — of the interpretations of our Sages.”

Many commentators, including such Torah giants as the Mizrachi, the Maharal of Prague, the Baal Halevushim, and the Taz, have written books that discuss the subtleties of Rashi’s commentary on the Torah.

Of special note is the Lubavitcher Rebbe’s contribution to Rashi scholarship. In 1965, after the passing of his saintly mother, the Rebbetzin Chana, the Rebbe would dedicate a portion of his Shabbos talks to explaining a section of Rashi for that week’s Torah portion. He did this for more than two decades, bringing to light the full range of meaning encoded within Rashi’s often-terse words. Hundreds of his novel explanations are published in <<Likutei Sichos>>, his collected talks, as well as <<Biurim L’peirush Rashi>>, a five-volume set of books exclusively on the Rebbe’s Rashi novellae.

While Rashi’s commentary is essentially a collection of answers to the problems that one could raise about the simple meaning of the Chumash text, Rashi does not specify which question he is resolving. In order to teach Rashi’s commentary to the yeshiva students, Rabbi Wichnin put into writing some of Rashi’s questions on each Torah portions. Most questions will find their answer in one of Rashi’s commentaries of the Torah.

These questions stimulate and challenge the mind. Even after mastering the simple meaning, the student who uses _The Chumash Questions_ will come to appreciate Rashi in a new light. And in so doing, he or she will not only gain insight into Rashi’s commentary, but an even greater insight into G-d’s Torah.

