[#notes]
[preface]
== Notes

[discrete]
=== Holiday Questions
In addition to the Chumash Questions, Rabbi Wichnin also supplied his students with worksheets on the Jewish festivals, high holidays, and Chassidic holidays. These questions range from very simplistic to quite sophisticated, in order to accommodate the variety of yeshiva students. For most of the simple questions, the beginning student will find the answers in the Kitzur Shulchon Oruch and for some of the more difficult questions, the more advanced student will find the answers in the Shulchon Oruch of the Alter Rebbe. The halachic worksheets were obviously geared to the newcomer; nonetheless, everyone can benefit from these questions as preparation for the holidays.

[discrete]
=== Editing
This publication is designed to be an accurate rendering of the author’s original work, which consisted of loose handouts intended for internal yeshiva use. They were not edited by the author nor prepared for publication and should, therefore, be viewed in this light.

[discrete]
=== Typographic Conventions
For the convenience of the reader, Hebrew words are italicized the first time they appear in the text. (These first mentions are often followed by a definition in parentheses.) Subsequent occurrences are set in standard (roman) type.

[discrete]
=== A Special Request
The Wichnin family asks that if anyone has personal stories, memorabilia, letters, pictures, etc., to please forward a copy to them at:

    Wichnin Family
    119 West Maple Avenue
    Monsey, NY 10952
