[#devarim]
=== Devarim

. Why doesn’t Moshe state his words of rebuke *clearly* instead of just hinting?

. “To all the Jews,” etc. Why was it necessary to gather them *all* here?

. Which words hint at the following sins of Bnei Yisroel:
[upperalpha]
.. Making the golden calf
.. Their complaints about the mon
.. Their complaints at the Yam Suf
.. Their idol worship of Peor
.. The rebellion of Korach
.. The sin of the spies

. Why did Moshe choose to rebuke them only when he was at the end of his life?

. Who else before and after Moshe rebuked close to his last days?

. “After he conquered Sichon and Og,” etc. Was this necessary for the rebuke? How?

. On which date did Moshe begin his review of the Torah? For how long?

. How did Moshe explain the Torah to them? (In what language?)

. Why is the River Pross called the ‘Great River’?

. “I cannot carry you by myself,” etc. Why? Who else said the same? For the same reason?

. What is meant by, “And you are today like the stars”? That many?

. “Come and inherit the land,” etc. But didn’t they have to prepare weapons and *fight*?

. “He should add upon you a thousand fold.” Why does it then say, “and bless you”?

. How were some Jews uncooperative in court cases? In their view of Moshe’s conduct?

. What example from a banker is given to explain the two kinds of ‘wise men’?

. Why did Moshe say get me judges (candidates) *who are known to your tribes*?

. On whom are the nation’s failures blamed? Why? Is Moshe included?

. What was Moshe’s complaint about Bnei Yisroel’s response on the appointment of judges?

. “And *I took* the heads of your tribes,” etc. How did he *take* them?

. There were seven qualities of good judges. How many were found? Which one is missing here?

. Which precaution for judges is mentioned here that is also mentioned in Pirkei Avos, Ch. 1?

. What kinds of honors are the people obligated to display for the judges?

. To whom is this warning directed: “Don’t recognize faces (favorites) in judgment?”

. “Listen to large and small alike,” etc. What are the *three* meanings here?

. How does a wrong judgment affect Hashem? Why is it mentioned here?

. Moshe and Shmuel were both punished for putting themselves above others. How?

. In how many aspects do monetary and capital court cases differ?

. Mention is made here of two episodes when a mass of people approached Moshe. One was done properly and one was not. When? How?

. Moshe says *he* liked the idea of spying the land. Why then is he rebuking them?

. The report of the spies is presented here differently than before. How?

. Why did the people say that Hashem doesn’t like them? Was it true? How?

. The fact that we got Eretz Yisroel was disliked by some people. Why? What example of two fields is used here?

. Moshe said to them: “Don’t be afraid!” What proofs did he offer?

. Where did Hashem clearly show that he treated us like a father?

. What part of the land did Kalev receive? Why?

. Moshe makes a point that the people were wrong about their children. How?

. “And they pursued you like the bees do.” What’s the comparison?

. “And Hashem, *the Merciful One* didn’t listen to you.” Why the emphasis here?

. There was a place where the people dwelt as long as in all the others combined (during their travels in the desert). Where?

. “I will not give you even a footstep of their land.” Whose land? Why is the expression ‘footstep’ used here?

. Avrohom received ten lands from Hashem. Which now and which later?

. Lot got two of these lands for now, because of a good deed. Which?

. Moshe told them not to hide their riches in front of the nations. Why?

. Two warnings were given to our nation against attacking two nations. How? Why?

. Why was the removal of the old generation speeded up in the desert?

. Prove that Hashem’s spirit rests on the prophet *only* in honor of Bnei Yisroel.

. The people called <<Refayim>> (why?) lived in two lands. Which?

. The people called <<Kaftorim>> destroyed the people called <<Avim>>. Why is this mentioned here?

. Prove that the sun stopped in the sky for Moshe as it did for Yehoshua.

. How did Moshe figure out that it is proper to offer peace to Sichon?

. Hashem says to Moshe, “Look, *I started giving you Sichon* and his land.” How?

. How did Hashem cause Sichon to reject Moshe’s peace offer? With which other king did Hashem do the same thing?

. Why didn’t Sichon ask Og to help him in his battle against the Jews?

. in both wars against Sichon and Og, the Jews took lots of spoils but they felt differently about them. Why?

. In the war on Og, Moshe was told not to fear the enemy, but not in the war on Sichon. Why?

. Mount Chermon (now in Israel’s hands) had four names. Why?

