[#ki-seitzei]
=== Ki Seitzei

. How many types of war are discussed in the Torah? Which one is mentioned here?

. If a person from the ‘seven nations’ is captured, can he be used as a servant?

. “The Torah only spoke (here) against the yetzer horah.” Were is this applied?

. Besides conversion, what are the other things the captured women must do to marry?

. What will be the future of this kind of marriage according to the Torah?

. What kind of children is this woman likely to have? Proof?

. The oldest brother takes a double portion. But sometimes he doesn’t. When?

. The rebellious son (<<ben sorer umoreh>>) gets the death penalty. Why?

. Previously he got a lesser punishment. What was it? What crimes did he commit?

. How is the next subject in the Torah connected to that of the ben sorer umoreh?

. What reason is given for honoring the body of even a sinful person?

. If one sees a lost item on the street may he just ignore it (look away)? Ever?

. If a lost animal is found, should he be sold or kept (in order to be returned)? Why?

. What if you find a wallet on yeshiva grounds - can you use it?

. In what case can you be exempt from helping a Jew to lift a load?

. What kind of prohibition is there on men’s and women’s garments?

. If someone tells you the location of a bird nest, can you go there to do a mitzvoh of <<shiluach hakan>>? Reason?

. Can one take (and use) the mother bird *after* sending her off? Proof?

. What is the reward for this mitzvoh? How about ‘harder’ mitzvos?

. What is the connection between the parshiyos of shiluach hakan, <<kilayim>> (mixing seeds), kilayim in plowing, kilayim in garments, and tzitzis?

. If the man was destined to get hurt why should the house owner make a fence?

. Which manner of planting grain and vines is forbidden by the Torah?

. What is *incorrect* in this statement, “Only an ox with a donkey are forbidden to be used together, and only in planting.”

. Why is the mitzvoh of tzitzis written following the prohibition of shatnez?

. Prove that one aveiro leads to another. How is this stated in Pirkei Avos?

. Prove that the Torah considers a child’s (even a grown child’s) behavior a reflection of his or her upbringing.

. What are the two penalties for a <<motzi sheim rah>>?

. Who is punished more severely, an engaged women or a married woman who sinned?

. “A break in the wall (of modesty) invites the criminal.” Where is this exempt?

. Prove that forcing someone to sin is considered like killing him.

. Prove that when you’re really forced into an aveiro, you are exempt from punishment. What is the Hebrew term for this kind of aveiro? Other kinds?

. What kind of (Jewish) person may never marry a Jew (by birth)?

. Two reasons are stated why men (only) from Amon and Moav may not marry Jewish women.

. Edomite and Egyptian converts may marry Jews a little later. When?

. Why is the Torah more strict with Amon and Moav than with the Egyptians?

. Prove that the Torah wants us to be thankful for a favor eternally

. Prove that the one who causes a person to sin is doing a bigger harm than if he had killed him. Give a reason for your answer.

. Someone who did good things to you at first, but then became cruel to you — should you remember both, forget both, or remember one? Proof?

. Nowadays, if an Egyptian convert wants to marry a Jew, may he (or she)?

. Why is special care to avoid tumah necessary in war-time?

. A person must keep the area around him clean even in hard times. Proof?

. What is the right thing to do if a runaway slave comes to you?

. Give a case where a good, healthy lamb is disqualified for a korban.

. How many aveiros are done when one takes *interest* from a Jew?

. When promising to bring a korban as a donation, how long may you delay it?

. A person who is working in someone’s vineyard, may he eat lots of grapes?

. How does a divorce (<<get>>) proceed? May the divorced couple remarry each other?

. The first year of marriage, the exemption from the draft is bigger than other exemptions. How?

. What kind of security (for a loan) may not be taken? Why?

. If someone kidnaps a Jew and sells him, what is his punishment?

. There was a great tragedy in our history that was connected to the above. Can you guess which?

. Why is Miriam’s leprosy mentioned here?

. In what *manner* are we forbidden to take security (<<mashkon>>) from the borrower?

. Sometimes we must keep returning the security daily. Explain.

. Is there a difference in the gravity of the aveiro of withholding wages from a rich worker or a poor one? Proof?

. Is there a difference whether a verdict is tilted for a rich or a poor man?

. Why is the exodus from Mitzrayim mentioned here?

. There is one mitzvoh which can *never* be done with kavana! Which?

. Do we give <<pe’ah>> from fruit trees? Proof?

. What is *incorrect* in this statement: The prohibition against muzzling (closing the mouth) of animals is applicable only ‘for an ox while he threshes the grain’?

. Why is the subject of <<malkos>> written next to the above prohibition?

. Prove that it is against the Torah law to hit a person (even a bad person).

. In what cases does the mitzvoh of <<yibum>> *not* apply?

. And where does <<chalitzah>> apply? How is it done?

. What is Amalek compared to?

. Why is it written next to the section on correct weights?

. Prove that cheating in business brings losses and honesty brings blessings.

