[#mishpatim]
== Mishpatim

. “And these are the laws,” etc. What are the *two* connections to the previous <<parsha>> (<<Yisro>>)?

. In what connection is the term <<shulchon-oruch>> mentioned in the first <<posuk>>? (See <<Rashi>>.)

. What is wrong with bringing a dispute to the non-Jewish courts?

. How was the <<eved-ivri>> purchased? Would the law be different if he sold himself?

. What kind of <<eved>> can get a <<shifcha-cnaanis>>?

. What happens to this <<shifcha-cnaanis>> after the <<eved>> goes free? Source?

. What if the <<eved-ivri>> refuses to leave until after six years?

. Can an <<eved-nirtza>> be a slave forever? Until when? Source?

. Which ear is pierced? Why the *ear* (not the nose)? (Different reasons for different <<avodim>>, slaves).

. The door and the door post are connected with piercing the ears. How? Why?

. Which kind of child may the father sell into temporary slavery? Can a mother sell too?

. How do non-Jewish slaves (men and women) go free from slavery?

. How does a young girl go free from slavery? (Three or four ways.)

. Explain these terms:
<<yiud>>,
<<simanim>>,
<<naarus>>,
<<bagrus>>,
<<shear>>,
<<kesus>>,
<<onah>>.

. Which two laws in the punishment for killing do we derive from <<posuk>> 12?

. Why does <<Hashem>> make it happen that one person should kill another? Find a parallel to this thought in <<pirkei-avos>>.

. If a doctor mistakenly kills his patient or a father his son are they punished? Source?

. What reason would you give a doctor not to operate on his parents?

. Which person gets the death penalty just for saying some words?

. What kind of thief gets punished by death?

. What kind of payments are required if one maimed a person?

. Explain these terms: <<nezek>>, <<tzaar>>, <<ripuy>>, <<sheves>>, <<boshes>>.

. If the master (or a stranger) kills a non-Jewish slave, what is his punishment?

. If one kills a pregnant woman, what is his punishment? What if she survived the attack?

. “An eye for an eye,” etc. How do we prove that it means monetary payment? (See <<Gemora>> <<Baba-Kama>> p. 84.)

. The knocking out of a eye or a tooth sets a slave free. Which other limbs do the same?

. If someone’s lion (or chicken) kills a person, what happens to the animal? What happens to the owner?

. When a person’s ox kills another ox what happens to the owner?

. Explain the terms: <<mazik>>, <<nizak>>, <<tam>>, <<muad>>, <<kofer>>.

. When a person makes a pit (<<bor>>), which kind of damages is he responsible for?

. For which kind of stealing does the thief pay 4 times as much? 5 times? Why this difference?

.  If a thief who dug into a home gets killed by the owner, is there a punishment? Why?

.  What happens to a person whose fire went and damaged others’ property?

.  If animals went and trampled or ate someone’s grain, who pays for it?

.  If a <<shomer-chinam>> claims the article was stolen, what happens to him?

.  In the case of a <<shomer-sachar>>, when is he held responsible?

.  A person who is a <<shoel>>, could he ever be exempt from payment?

.  What about a person who rents a tool from someone (a <<socher>>), how is he responsible?

. For which kind of worship-of-idols does one get the death penalty?

. What kind of prohibitions are written concerning a <<ger>>? Reason?

. What are the punishments for the mistreatment of orphans and widows?

. Which are the priorities for *lending money*? What two prohibitions are connected with it?

. What comparison is made between the soul (<<neshamah>>) at night and taking a pledge?

. Where is the <<din>> of <<modeh-bemiktzas>> derived from?

. What are the warnings given about <<bikurim>>, <<terumah-term>> and <<maaser>>?

. Why is the <<din>> of <<pidyon-ha-ben>> mentioned here again?

. “And *holy people* you shall be unto Me…”, etc. How do we become holy?

. How do we see that <<Hashem>> does not diminish the reward of any creature?

. Within the same <<posuk>> are contained warnings to a judge, and about <<loshon-horo>>. What are they? What is the connection between these two?

. When do we need a majority of one judge and when is a majority of two necessary for a verdict?

. The non-Jews (idol worshippers) are in the majority, while we are the minority. Why don’t we follow them?

. Where is there a prohibition, against treating a poor man *too well*?

. Why is an “enemy” mentioned by the <<mitzvoh>> of <<Prikah>>? When are you exempt?

. After a verdict when do we return the defendant for rejudgement and when not? Why?

. What are the punishments of a judge who takes bribes to judge *correctly*?

. Which entire year is called ‘<<Shabbos>>’? Why? Do we still keep in it the regular <<Shabbos>>? Source?

. It was said that one who uses *forbidden conveniences on <<Shabbos>>* claiming that he *enjoys it* is compared to an ox. How?

. How should one avoid any references to idols in giving travel directions? In partnerships?

. What names are given here to the holidays of <<Pesach>>, <<Shavuos>>, and <<Sukkos>>? Why?

. Which warnings are given here about the <<korban-pesach>>? About <<bikurim>>?

. Why did the <<Torah>> write three times “don’t cook the goat in its mother’s milk”?

. “… Behold I am sending an *Angel*…”, etc. Why? What warning is given here in that connection (in the next <<posuk>>)?

. If the last <<parsha>> here was actually said before <<matan-torah>>, what does it mean “all the laws”? “and <<Moshe>> wrote down all the words of <<Hashem>>”?

. The Sages said: “from here we know that our ancestors entered the covenant with <<milah>>, <<tvilo>>, and sprinkling of blood”. How do we know?

. What “sights” did the elders see? Did they get punished for it? When? Why? Which five words in the <<posuk>> tell us this?

. What did <<Rabbi-Sadya-Gaon>> find in the Ten Commandments?

. Why is <<Yehoshua>> mentioned here? And why <<Chur>>? Where was <<Moshe>> called to?

. What are the opinions about the six days that <<Moshe>> was covered by the cloud? Why was <<Moshe>> called on the seventh day?

. Why do we read <<parshas>> <<Shekalim>> this <<Shabbos>>?

. Who was obligated to give <<machatzis-ha-shekel>>?

. What were these <<Shekalim>> used for at the <<Mishkan>>?

. Do we have any <<minhag>> of <<machatzis-ha-shekel>> today?

. Usually each person gives according to his ability. Why not *here*?

. How many <<Torahs>> are taken out this <<Shabbos>>? Why?

. In which portion is the <<parshas>> <<Shekalim>> found?

. What is the (general) content of the <<Haftorah>> for this <<Shabbos>>?

. Which are the *other three* special <<Parshios>> we will read (on other <<Shabbosim>>)?

. What special saying of our sages describes our mood this month (get to know the Hebrew words)?

. Why is this month more special than other months?

. When is <<Rosh-Chodesh>>? How many days of <<Rosh-Chodesh>>?
