[#bechukosai]
== Bechukosai

. What proof is there that the first <<posuk>> here refers to toiling in Torah?

. How is the above connected to the next phrase, “You shall keep My mitzvos”?

. The rain comes in the right (convenient) time if it comes... *when*?

. What *special blessing* is given about certain trees? About eating bread?

. Which blessing equals the goodness of all other blessings combined?

. “And a sword will not cross your land,” etc. Isn’t this a repetition of the peace blessing?

. The enemy will “fall by the sword,” in a special, miraculous way. How?

. “Five will pursue 100, and 100 will chase 10,000.” What is the difficulty in this <<posuk>>? And the answer?

. “And i shall turn to you,” etc. What kind of reward is promised here?

. What kind of *family* and *personal* (physical) blessings are mentioned here?

. “And I will establish my covenant with you.” Didn’t we already have one?

. How does the Torah describe the *large harvests* that will come as a reward?

. Name two *spiritual* blessings mentioned here.

. Why does Hashem mention *here* the fact that He took us out from <<Mitzrayim>>?

. There are seven <<aveiros>> which follow one another. Which are they?

. Why do the punishments come in sets of seven? (See <<posuk>> 18.)

. Lack of rain is a punishment. How is the one here worse than the one Moshe said in the punishments of Ki Savo?

. What kinds of bad attitudes are described in <<posuk>> 21?

. There is a specific punishment about baking bread. What is it?

. In <<posuk>> 32 there is a punishment that is also a comfort. Explain.

. Which sin is atoned for by the punishment of the land being desolate?

. How many years after the exiling of the ten tribes did the total destruction come? Which were the last two tribes to be exiled? Where did they go?

. Give the count which explains the reason for the 70 years of <<galus-bavel>> (Babylonian Exile).

. How do we see that the Torah holds each Jew responsible for his friend’s sins?

. In <<posuk>> 37 there is a comforting promise made to the exiled Jews. What is it?

. What kind of a ‘letter’ exchange is there between Yaakov and Eliyahu? What for?

. “My covenant with Yaakov,” etc. Why are the names of the <<Avos>> mentioned in reverse order?

. Why is the word ‘remembrance’ *not* mentioned in connection with Yitzchak’s name?

. “And the *Torahs* which He gave,” etc. Why is it written in plural form?

. How is the value of a person estimated for purposes of <<tzedakah>> (<<hekdesh>>)?

. On which difficult word does Rashi say, “I don’t know where it comes from”?

. How do we see that old age affects a man more negatively than it does a woman?

. What is the saying brought from the Gemora, describing the above conditions?

. What is done when a contributor cannot afford to pay the full value?

. Can a person donate just the foot of an animal to the <<beis-hamikdash>>? Explain.

. How do we know that we may not exchange one animal (donated for a <<korban>>) for another, even one of equal value?

. Can a donated animal that became blemished be redeemed? Explain.

. How do we estimate the value of a field for redemption purposes?

. What kind of donated (<<hekdesh>>) *field* returns to the owner in <<Yovel>>? Which doesn’t?

. What kind of kosher and healthy animal cannot be donated to <<hekdesh>>? Why?

. If a person donates a <<tomei>> (non-kosher) animal to <<hekdesh>>, what is done with it?

. When a person donates his possessions without specifying to whom it is given, who gets them? (Two opinions.)

. Sometimes donating the value of a human to <<hekdesh>> is ineffective. Why?

. What kind of <<maaser>> must be eaten in Jerusalem? How is it stated in the <<posuk>>?

. What difference is there whether one redeems *his own* <<maaser>> or *someone else’s*?

. What kind of <<maaser>> is designated by using a whip? What is done with this <<maaser>>?

. If the tenth animal has a blemish, what is done with it?

. Where is there a hint in these <<pesukim>> about Yud Shevat?

. Who gets the of <<aliyah>> of the <<tochecha>> (curses, punishments)? Is he called up?

. Why do we say ‘Chazak’ at the end of every <<Chumash>>?

