[#metzorah]
== Metzorah

. Can the metzorah be cleansed at night? Proof?

. The metzorah is put outside of the camp (or city). How does the <<Kohein>> see him?

. Can you bring an example from the <<mivtzoyim>> which is similar to the above?

. Why does the metzorah bring *birds* for his cleansing?

. The species of the birds is not mentioned. Which birds are not acceptable?

. Why does the metzorah bring the [.verse]#etz erez#{ltr}, [.verse]#shei#{ltr}, [.verse]#tolaas#{ltr}, [.verse]#ezov#{ltr}?

. What is done with the *two birds* (with the items from the previous question)?

. What does the metzorah do on the *first* day of his cleanliness? On the *eighth*
day?

. On which parts of the metzorah’s body do they put the *blood*? The *oil*?

. From the ‘13 midos’ of Rabbi Yishmael (in <<Shacharis>>) we use three in this parsha. Which midos are used? How?

. Rashi says he doesn’t know why a certain thing is called by its name. Which?

. A metzorah who is poor, how are his <<korbanos>> different?

. Why is it *good news* that some homes in Eretz Yisroel have <<negayim>>?

. Why does the Torah command to empty the house *before* the <<Kohein>> comes?

. What is done to the house when the <<negah>> is first seen?

. What happens to the person who *eats in* or *sleeps in* or *just enters* the closed house?

. If the <<negah>> grows bigger on the seventh day, what is done to the house?

. What is done for the house after the ‘new stones’ remain clean?

. An item which a <<zav>> touches, sits on, or sleeps on, what <<tumah>> does it get?

. When does a <<zav>> become <<tahor>>? What does he have to bring?

. What kind of <<tumah>> does a lady <<zavah>> cause?

. What kind of <<taharah>> is *common* in (almost) all cases?

