[#tzav]
== Tzav

. According to Rabbi Shimon, why does it say here ‘<<tzav-term>>’ (command) instead of ‘daber’ (speak)?

. What does <<posuk>> 2 tell us about the fats and limbs?

. If something became <<posul>>, does it still burn on the <<mizbeyach>>?

. What was the <<avodah>> of <<terumas-hadeshen>>? When did the <<Kohein>> change garments?

. Where was the fire for the <<menorah>> lighting taken from? Proof?

. There were two general kinds of <<korban-minchah>> that the Israelites brought. Which?

. If the [.verse]#kometz#{ltr} from the above Menachos was taken without <<kavana>> (intention), is it OK?

. Can blemished <<Kohanim>> eat from the Menachos? Proof?

. There was a certain <<korban>> that regular <<Kohanim>> brought during their dedication and the <<kohein-gadol>> brought every day. Which was it?

. Who ate the <<korban-minchah>> that <<Kohanim>> brought? Proof?

. What can we learn about koshering earthenware and metal dishes from that which is written regarding the <<korban>> <<Chatos>>?

. Which of these are <<kedoshim-kalim>> and which are <<kodshai-kedoshim>>: <<Chatos>>, <<Olah>>, <<Asham>>, <<Shlomim>>, <<Minchah>>?

. How long is the ‘eating time’ for a <<korban>> <<Shlomim>>?

. When is eating a <<korban>> punishable by [.verse]#koreis#{ltr}?

. What is the punishment for eating <<cheilev>> (forbidden fats)? Blood?

. Which parts of a <<korban>> <<Shlomim>> are given to the <<Kohanim>>?

. On which commandments does Rashi comment: “There is not (necessarily) a chronological order in the Torah”? Why here?

. “Take Aharon,” etc. How is Moshe supposed to take him?

. “And gather the community at the door of the <<ohel-moed>>.” What for?

. What special miracle occurred at this gathering?

. Why does Moshe repeat here: “This is the thing that I was commanded to do”?

. On which activity does Rashi remark, “I don’t know where he was commanded on it.”

. The <<mizbeyach>> was *cleansed* and *sanctified*. Why both things?

. Besides the <<shemen-hamishcho>>, what else was put on Aharon and his sons?

. One part of a <<korban>> was burned on the <<mizbeyach>> *only during the [.verse]#miluim#{ltr}*. Which?

. Where is there a hint here about the separation of the <<kohein-gadol>> before Yom Kippur?

. “And Aharon and his sons did all the things,” etc. What is the special compliment here?

. What is the special name given to this <<Shabbos>>? Why? Special customs?

