[#vayikra]
== Vayikra

. “And He called,” etc. Why did Hashem *call* Moshe before speaking to him?

. How was the appearance of Hashem to Moshe different than to Bilam? Why?

. Who else *calls* one another? Why? Where do we mention it in davening?

. What were the breaks? Their purpose? Was Moshe *called* at these breaks? Why? What do we derive from this about our learning?

. “And Hashem spoke in *him*.” Who is excluded here?

. Was the voice of Hashem high? How far did it reach? Who *didn’t* hear it?

. Why is *Adam* mentioned in connection with the <<korbanos>>?

. There are six categories of <<pesulim>> in <<korbanos>>. Which?

. If an <<Olah>> gets mixed in with other sheep, what happens?

. If a person promises an <<Olah>> then refuses to give it, do we force him? Proof? *How* do we force him? (See Rambam, Laws of Gerushin 8:2.)

. If we do force him, how can the <<korban>> be ‘according to his will’?

. For which kinds of sins does a <<korban>> <<Olah>> atone?

. Can a non-<<Kohein>> slaughter the <<korban>>? Take the blood? Proof?

. “They should put fire,” etc. But wasn’t there a fire sent from heaven?

. if a <<Kohein>> is ‘too well dressed’ or ‘not so well dressed’ his <<avodah>> is <<posul>>. Explain and give proof.

. What are the requirements for a <<korban>> of fowl (pigeons, doves) to be kosher?

. Why are the insides (intestines) of fowl thrown out, and not those of sheep?

. Why are the doves burned on the <<mizbeyach>> with their *wings*?

. Regarding both sheep and fowl, it says, _‘Reyach nichoach laShem.’_ What does this teach us?

. Why does it say _‘Venefesh ki sakriv’_ only in reference to a <<korban-minchah>>?

. Which parts of a <<korban-minchah>> could be done by non-<<Kohanim>>? Which part must the <<Kohein>> do?

. The fistful is called a *reminder*. For what?

. Did the <<kohein-gadol>> and regular Kohein get the same portions? Explain.

. What are the two opinions concerning the application of oil on a <<Minchah>>?

. What kind of oil is kosher for Menachos? Proof?

. What two items cannot be brought with a <<korban-minchah>>?

. All <<korbanos>> required *salt*.Why is this called <<bris>> (covenant)?

. Most Menachos are voluntary except one. Which?

. Why are certain <<korbanos>> called <<Shlomim>>? (Two reasons.)

. The daily <<Tamid>> had to be the first <<korban>> of the day. Proof?

. For which kind of sins is a <<korban>> <<Chatos>> required?

. If a person writes part of a word on <<Shabbos>>, does he bring a <<korban>> <<Chatos>>? Proof?

. When a <<kohein-gadol>> sins, why is this called the ‘guilt of the nation’?

. What kind of situation is described in <<posuk>> 4:13?

. Prove that Hashem loves <<Am Yisroel>> (the Jewish nation) more than He loves the <<kohein-gadol>>.

. What kind of <<aveiros>> (sins) are described in <<pesukim>> 5:1-3?

. Which kind of <<korban>> do all *those* people (in question 36) bring?

. When an <<Olah>> and <<Chatos>> are brought, which goes first? Why?

. If a person was rich when he sinned, and then became poor, which kind of <<korban>> is he required to bring? (And if vice versa?) Explain.

. What kind of aveiro is described in <<posuk>> 5:15?

. What kind of <<korban>> <<Asham>> is mentioned in <<posuk>> 5:18? Its purpose?

. For which kind of <<aveiros>> does this <<Asham>> atone?

. What kind of lessons do Rabbi Akiva, Rabbi Yosai, Rabbi Yosai Haglili, and Rabbi Eliezer learn from here?

. According to Rabbi Akiva, why is one who denies a deposit worse than one who denies a loan?

. What kind of <<aveiro>> is described in Chapter 5, <<posuk>> 22?

. How many kinds of <<korbanos>> are mentioned in this Parsha?

. There are two very famous <<maamorim>> in <<likutei-torah>> on this Parsha on Chapter 1, <<posuk>> 2, and Chapter 2, <<posuk>> 13. See what it says there.

. Which <<korbanos>> from this Parsha are mentioned in the daily <<korbanos>> portion of <<tfilas>> <<Shacharis>>?

[discrete]
==== Extra
[start=49]
. What do we have today instead of the <<korbanos>> (two general things)?

. How does the <<maamar>> <<basi-legani>> of <<yud-shvat>> explain the subject of <<avodas-ha-korbonos-b-ruchnius>>?

. Why is aleph in the word '<<Vayikra>>' a small one?

. How many <<mitzvos-asei>> and <<mitzvos-lo-ta-asei>> are mentioned here?

. What other name is given to this <<Chumash>>? Why?
