[#masei]
=== Masei

. “These are the travels,” etc. Why are they all written here? (Give the opinions of Rabbi Moshe Hadarshon and Rabbi Tanchuma.)

. “On the *morrow* of Pesach the Jews went out” (33:3) But didn’t they leave on Pesach itself?

. Why does it mention here that the Egyptians were “burying their dead,” etc.?

. The original name of Midbar Paran is changed here to <<Risma>> (33:18). Why?

. How old was Aharon when he passed away? How did he die?

. “And the Cnaani King of Arad heard,” etc. Why is it mentioned here?

. How many stations along their travels are mentioned here?

. Posuk 49 mentions the space occupied by the camping tribes. Why?

. Why is the warning to drive out the nations from Eretz Yisroel repeated here?

. Yehoshua repeated the same warning to Bnei Isroel. Where? Why?

. What will happen if the Jews don’t drive out their enemies?

. What is the purpose of describing the borders of Eretz Yisroel?

. Why does it say, “This is the land that will *fall* to you,” etc?

. At the time of the Exodus what could have been the shortest route from Mitzrayim to Eretz Yisroel? Why weren’t they taken along this route?

. Into how many tribes was Eretz Yisroel divided? Why?

. The Torah enumerates the heads of tribes that will parcel out the land for their tribe members. Which tribes are not mentioned?

. The open spaces around the towns of the Levi’im were allowed to be used only for some purposes, but not for others. Which?

. What purpose did these towns serve besides residences for Levi’im?

. Even though Moshe set aside three cities of refuge (<<arei miklot>>), they didn’t function until later. When? Why then did Moshe set them up for this purpose?

. The two-and-a-half tribes on the east side of <<Yarden>> (Jordan) got the same amount of cities of refuge (three) as the entire land of Israeli Why?

. What might have happened if they didn’t set aside cities of refuge?

. “And if he killed him with an iron tool,” etc. What kind of a murder is meant here?

. Why is it not mentioned here how big the iron tool has to be, as it says for stones and wood?

. In a case of unintentional killing, sometimes the killer is not exiled. When? Proof?

. If the avenger of the blood (<<goel hadam>>) kills the murderer outside of the cities of refuge, is he punished? Why?

. When can the murderer leave the city of refuge? Why? (Two reasons.)

. What type of murderer has to wait until the death of two Kohanim Gedolim to get out? Proof?

. Can a murderer be punished (killed) on circumstantial evidence? Proof?

. In what connection is ransom mentioned in this subject?

. Did they have a Sanhedrin outside of Eretz Yisroel? When?

. Why is there such a strong warning against making the land impure?

. The heads of the Gil’ad family approached Moshe with certain concerns. What were they?

. What was Moshe’s response about Bnos Tzlafchad and other daughters that inherit parts of the land?

. “And if the Yovel will come,” etc. What did Rabbi Yehuda learn from this?

. According to Rashi, in what order are the daughters of Tzlafchad listed here and elsewhere?

. Can you find a contradiction between this statement of Rashi and his comments in parshas Pinchas? How can it be resolved?

. The prohibition that a daughter inheriting a share of the land may not to marry out of her tribe, was not a permanent one. Explain. (Check the Rashi in parshas Pinchas for this halacha.)

. When is Rosh Chodesh? What special period starts then?

