[#pinchas]
=== Pinchas

. Why is it mentioned here (again) that Pinchas is the grandson of Aharon?

. In the words of the posuk, what did Pinchas do for Hashem? For the nation?

. What reward did Pinchas get for his brave act? (Two things.)

. Wasn’t Pinchas automatically a Kohein by being a grandson of Aharon? Why?

. Why is it mentioned who Zimri’s father was and his position? (Two reasons.)

. Why is the family and position of Kozbi (the Midyanite woman) mentioned here?

. Only Midyan was to be punished and destroyed, not Moav. Why?

. Why were Moshe and Aharon commanded here to count the people? (Two reasons.)

. Why are the names of the families in each tribe written with the letters <<hai>> and <<yud>>?

. When did Korach’s sons repent? What happened to them?

. How many families are counted here (with Levi)? How is this number connected with the statement, “You are the smallest of all nations”?

. There is a name mentioned here even though it is not connected with a family. Whose? Why is it mentioned?

. Is the total number here the same as the number in parshas Bamidbor?

. From what age did a person get a share in the land? When was this age supposed to be reached (before or after entering the land?)

. By which estimates was the land partitioned into twelve sections?

. How was it divided among the twelve tribes? (Two methods.)

. How is this inheritance assigned differently than a usual inheritance?

. Which people were not included in the lots for division (besides women)? Why?

. Which person had the <<zechus>> (merit) to complete the number 70 for the Jewish people in Mitzrayim? Proof?

. Who wasn’t counted among the rest of the nation (only separately)? Why?

. Prove that there were many more women than men in the nation at this time.

. Five smart girls had a complaint to Moshe. Who were they? What was their complaint?

. Why is it mentioned that they were from the family of Yoseif? (Two reasons.)

. Why does the order of the girls’ names change in two places?

. How do we know that their case came up on the fortieth year?

. What is the dispute between Rabbi Yashiya and Aba Chonon here?

. Why did they have to say that their father was not among the sinners?

. For what sin did he die? (Two opinions.)

. What was the girls’ proof that they should be considered like sons?

. Why didn’t Moshe have the answer for them? (Two reasons.)

. How do we see that these girls saw something that Moshe didn’t see?

. How many portions did they get? Proof?

. Why is there a special expression (for transfer) regarding a daughter’s portion?

. Why is the portion telling Moshe about his passing written here? (Two reasons.)

. Why does it say, “As your brother Aharon passed away”?

. What is the order of preference for inheritance?

. Why does the Torah always mention the reason for Moshe and Aharon’s passing?

. Moshe is asking about a successor. Why here?

. What was the reason for Yehoshua’s choice?

. Why does he mention that Hashem knows everyone’s mind?

. “That will go out before them.” What does it mean here?

. “That will take them out and bring them in.” How?

. How should Moshe ‘take’ Yehoshua?

. How should Moshe demonstrate (in front of the people) that Yehoshua was chosen?

. What should Moshe tell Yehoshua about the people?

. What did Moshe have to do to put his spirit on Yehoshua?

. How do we learn that Moshe’s face was like the sun and Yehoshua’s face like the moon? What are the Hebrew words for these?

. How was Moshe’s request about his own family having leadership fulfilled by this transfer?

. How did Moshe convince Yehoshua about the greatness of this position?

. Moshe did more for Yehoshua than he was asked. How?

. Why is the subject of the sacrifices written here?

. How do we know that not only Kohanim but also Levi’im and Yisroelim were to be present at the daily korban? How was their presence arranged?

. How do we derive that the morning Tamid was to be done on the western side and the evening Tamid on the eastern side of the area designated for sacrifices?

. “The Olah that was brought at Har Sinai.” Which one?

. Which part is called ‘My bread’? Which is ‘My korban’?

. Which two kinds of wine are not kosher for Nesochim? Proof?

. If one Shabbos korban is missed, can it be made up the next Shabbos? Proof?

. When is the proper time of day for the offering of the Korban Musaf on Shabbos and Yom Tov?

. What kinds of sins are atoned by the Korban Musaf?

. Which sin is atoned by the Korban Musaf of Rosh Chodesh? (Two answers.) Proof?

. What is the meaning of the three types they had to bring for the Korbanos Musaf: <<porim>>, <<eilim>>, <<kevasim>> (bulls, rams, lambs)?

. By what name is the holiday of Shavuos called here? Why?

. What was the special order for the korbanos (bulks) on the hoiiday of Sukkos? How many were there in total?

. On Sukkos, how many lambs did they bring in all? The significance of it?

. Where is there a hint about the special ‘pouring of water’ on Sukkos? What do we call it, and how do we celebrate it nowadays?

. What is the name for the 8th day of Succos? Reasons?

. What the good advice does the Torah give us about the Korbonos that were donated during the year (<<nedorim>>, <<nedovos>>)?

. What  is  the significance  of the single  ox and single  ram that we must bring on the day of Shmini Atzeres?

. Why does the Parsha end  off with the statement that Moshe spoke to the Jews “I all that he was commanded”?

. On which occasions do we read from this  Parsha (other than on Shabbos)?

. How many separate topics (subjects) can you find in this Parsha?

