[#purim]
== Purim

Based on the ‘Kitzur’ Siman 141, 142.

. How is the Fast of Esther different than the other fast days of the year in its reasons and observance?

. Why is it named <<taanis-esther>>?

. If a person eats on this day does he have to make up the fast?

. What is the reason for the <<machatzias-hashekel>>? How many are given? Why?

. What is the earliest time to read the Megillah at night? During the day? The latest? When is the right time for the other mitzvos of Purim?

. Where is the best place to read the Megillah? Why? Second best?

. What are the three blessings before the reading? And afterwards?

. What should listeners have in mind when these blessings are said?

. What *shouldn’t* you answer when you hear these blessings? Why?

. In the morning reading, what should you have in mind during the third blessing?

. How many words can you skip in listening and still be <<yotzei>> (exempt)?

. What’s the surest way to listen to the reading in order to be <<yotzei>>?

. Why does the reader (and everyone else) fold up the Megillah when reading?

. if you listen from a <<Chumash>>, is it better to say the words quietly? Why?

. If you already heard it and want to read for someone else, who makes the blessings? Why? Does it matter who the listeners are, men, or women, or children?

. On Purim morning, does the davening start early or late? Why?

. What part is read in the Torah? How many <<aliyos>> are there?

. Which is read first, the Torah or the Megillah? Why?

. How many food gifts must you send to do the mitzvoh of <<shalach-manos>>?

. How much money must you give (to how many poor people) to be <<yotzei>>?

. Which mitzvos of Purim are women exempt from? Why?

. Is there a mitzvoh to eat on the (first) night of Purim?

. When is the proper *time* to give <<matanos-la-evyonim>> and <<shalach-manos>>?

. Why is there a mitzvoh to drink more wine on Purim than on other holidays?

. Why is it especially proper to learn some Torah before the Purim meal?

. When is the right time to start the Purim seudah?

. If one forgets <<al-hanissim>> in davening or <<bentching>>, what should he do?

. Where is Purim celebrated on the 15th of Adar? Why? What is this day to us?

[discrete]
==== The Megillah
[start=29]
. In relation to the <<beis-hamikdash>> period, when did the story of Purim take place?

. The king Achashverosh was given to extreme mood changes. Give some examples from the story.

. The fact that Mordechai was one of the 71 Sanhedrin members helped him greatly. How?

. How do we know (according to our Sages) that Haman made decrees against observance of mitzvos?

. Mordechai and Esther announced three days of fasting. Which time of the year were they in?

. What are the reasons that Hashem’s name is not mentioned in the Megillah? (Two reasons.)

. Which <<posuk>> tells us that Jews re-accepted the Torah upon themselves at that time?
