[#shavuos]
== Shavuos

. What are the *five names* of this Yom Tov and their reasons?

. Why is there no specific date given in the Torah for this holiday? (How does the Torah describe the date for Shavuos?)

. Each of the five days prior to Shavuos the Jews did something in preparation for <<matan-torah>>. Can you describe them?

. What are the five symbols connected to <<matan-torah>> that are all connected with the number three?

. Who was born on Shavuos? Who passed away on Shavuos?

. What were the ‘two loaves,’ and what was done with them?

. On which day (of which month) was the Torah given? (Two opinions.) On which day of the week?

. <<bikurim>> are brought from the seven species of fruit. Can you name them?

. What is the ‘Torah reading’ for the first day? For the second? Why?

. Why is there a <<minhag>> to stay up the first night of Shavuos?

. Many communities say <<Tikun>> Shavuos night (and some study). Why?

. Why is there a <<minhag>> to daven <<Maariv>> *late* on Shavuos night?

. Which Haftaros are read on the two days? Why?

. How many days is Shavuos celebrated in Eretz Yisroel? In exile? Why?

. We do not say <<Tachanun>> from Rosh Chodesh until the 12th of Sivan. Why?

. How do we do the morning blessings (and <<negel-vasser>>) after staying up all night?

. Why is there a custom to decorate the home and the shul with greenery and/or flowers?

. What are the reasons for the <<minhag>> of eating *dairy foods* on Shavuos?

. Must we also eat meat on Shavuos? Why? How do we separate between the two?

. Which special prayer do we say on the second day of Shavuos? (Hint: Most children leave then.)

. What are two ways of reading the Ten Commandments in the Torah? Which one is used? Why? What is <<akdamus>>? Our custom?

. The Ten Commandments contain an open hint to the 620 mitzvos. What is it?

[discrete]
==== Matan Torah
[start=23]
. Who was offered the Torah before we were? What was their response? Why?

. Our Sages said that the entire creation was waiting for the Torah and shaking. Why?

. Who were offered by our nation as guarantors to Hashem for the observance of Torah and were rejected? Accepted?

. Which creatures desired to get the Torah? Why were they rejected?

. Why was the Torah given in the desert? Why on a low mountain?

. Which secrets from the Heavenly angels did the Jews find out?

. Why wasn’t the Torah given to us immediately after the Exodus?

. When we said ‘<<naaseh-venishmah>>’ (we shall do and we shall listen) we were immediately rewarded. How?

. What were the special miracles in the sights and sounds of <<matan-torah>>?

. Why were the Ten Commandments said in the singular (not plural) verb form?

. What are some of the differences between the Ten Commandments that are written in parshas Yisro and those in parshas Vo’eschanan?

. How was the Torah written down, at once or in stages? By whom? Where?

. Who divided the Torah into <<pesukim>>? Into sedras? Into <<aliyos>>? Into chapters?

. How many sedras are there? <<pesukim>>? Words? Letters?

. There are several types of letters in the Torah. What are they?

[discrete]
==== The Book of Ruth
[start=38]
. Why is Megillas Ruth read an Shavuos (in Tikum or in public)? Who wrote it? Why?

. Who was the father of Ruth? Who was her mother-in-law?

. Who was Boaz? How were he and Ruth related to King David?

. There were great acts of kindness in this book. What are they?

. Who was Orpah? Who was her grandchild? What can we learn from the difference between her and Ruth?

. Who was Elimelech? Machlon? Kilyon? From which tribe were they?

. Why were the above people punished? Why not Naomi?

. Which kinds of dinim do we derive from Megillas Ruth?

. How is Ruth related to Avrohom Avinu?

. Since Ruth came from Moav, whose people were forbidden to intermarry with Jews, how was she permitted?

