[#yom-kippur]
== Yom Kippur

. Why is <<kapores>> done (best) early in the morning?

. Can one do <<kapores>> with things other than chickens? If yes, with what?

. What mitzvoh is available at the time of the slaughtering?

. What if the slaughtering went wrong, do you have to get another chicken?

. What is the idea behind the custom of <<kapores>>?

. What is done with the slaughtered <<kapores>>? (Two possibilities.)

. What is the important mitzvoh on *<<Erev>>* Yom Kippur? Why?

. Certain sins are not forgiven on Yom Kippur. Which? What can we do for it?

. On <<Erev>> Yom Kippur we go to the <<mikvah>> three times (if possible). When are these done?

. All men should get <<makos>> (floggings) on <<Erev>> Yom Kippur. How? When?

. Lots of <<tzedakah>> is given on <<Erev>> Yom Kippur (according to your ability). Could you use <<maaser>>?

. We ask for honey-cake (<<lekach>>) on <<Erev>> Yom Kippur. Why? From whom?

. How much does one have to eat on <<Erev>> Yom Kippur? When is this done?

. The meal before the fast has a special name. What? Why?

. What is definitely avoided at this meal (though it’s important at the earlier meal)?

. It is best to finish the late meal at least one half-hour before sunset. Why?

. If is an important custom for parents to bless their children after candle-lighting (or close to it). Could you do it on the phone? Will you ask for it?

. If you want to eat or drink or brush your teeth after that meal, can you?

. Give two reasons for the custom or wearing (for married men) a <<kittel>> (white robe/coat) on Yom Kippur?

. What is the content of <<kol-nidrei>>? Why is it so important?

. Before <<kol-nidrei>> we quietly say the <<Vidui>>. This is the *second* time, When was the first?

. The second <<posuk>> of Shma (‘<<baruch-shem>>’) is said *loudly* on Yom Kippur. Why?

. When we say the long <<Vidui>> we mention sins we might not personally have done. Why do we say them?

. How many times of prayer do we have on Yom Kippur? What are their names?

. What do we read in the Torah in the morning and at <<Minchah>> time on Yom Kippur? Why?

. Maftir Yonah is very famous for being read at <<Minchah>> time; some people offer large sums for <<tzedakah>> to bid for it. What story is told there?

. The number of <<aliyos>> is greater on Yom Kippur than other holidays. How many are there? Why?

. We say <<Yizkor>> (after the first Torah reading) on Yom Kippur. Why?

. In what ways is Yom Kippur like <<Shabbos>> (instead of like Yam Tov)?

. What are the five personal physical needs that are forbidden on Yom Kippur? When is one *allowed* to wash (hands, etc.)?

. Who is exempt from fasting?

. Why isn’t Yom Kippur observed for two days as are the other <<yomim-tovim>>?

. What is the main mitzvoh for the day of Yom Kippur?

. What are the proper moods for us on <<Erev>> Yom Kippur and on Yom Kippur itself?

. At the end of the day’s prayers we repeat some <<pesukim>>. Which one do we do three times?

. What should we have in mind when we say Shma at day’s end? Why?

. When do we blow the shofar (one <<Tekiah>>) at day’s end? Why?

. When do we sing the joyous victory march and dance? Why?

. At day’s end we say something about Jerusalem. What? What do they say in Jerusalem?

. What is the proper greeting at the end of Yom Kippur? And in the days after?

. May we eat after <<Maariv>>? Meat? When do we wash <<negel-vasser>>?

. Weather permitting, we do <<kiddush-levana>> after <<Maariv>>. Why?

. How is the Shmoneh Esrei of this <<Maariv>> different from the Shmoneh Esrei of the past ten days?

. What is the most desirable activity after breaking the fast?

. Explain these terms:
[upperalpha]
.. [.verse]#avodah#{ltr}
.. [.verse]#ne'ilah#{ltr}
.. [.verse]#Duchenen#{ltr}
.. [.verse]#kohein-gadol#{ltr}
.. [.verse]#asara harugei malchus#{ltr}
.. [.verse]#chamisha inuyim#{ltr}
.. [.verse]#kori'in#{ltr}
.. [.verse]#Tevilohs#{ltr}
.. [.verse]#bigdei lavan#{ltr}
.. [.verse]#bigdei zahav#{ltr}
.. [.verse]#sei'ir la'azazel#{ltr}
.. [.verse]#gemar-chasimah-tovah#{ltr}
